-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Primary Trailheads (FMST's Google Sheet, as its CSV export) (FMST,
-- sources.json `fmst_primary_trailheads`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: The geometry alone: unique on 264 of 264 (measured 2026-10-04 on the
-- live export, every row parsed as extract/_gis_files.py parses it).
-- `Trailhead 1` is also unique; (`Eastbound Segment`, `EB Mile`) is 262 of
-- 264.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('fmst', 'raw_fmst__fmst_primary_trailheads'),
        ['geometry', 'trailhead_1']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'fmst_primary_trailheads'",
            geometry_key('geom'),
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
