-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- BLM National Public Lands Access Data (lines) (BLM, sources.json
-- `blm_public_lands_access_lines`): every row, keyed and deduped (decision
-- 40), with nothing filtered and nothing joined. A base model, the one
-- place this dataset is staged (decision 34).
--
-- Key: `GlobalID` is unique and non-null on all 4,835 rows read 2026-10-03.
--
-- Dates: acs_rghts_exprtn_dt, auth_dt, title_rec_dt, the layer's
-- esriFieldTypeDate fields (sources.json `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, acs_rghts_exprtn_dt, auth_dt, title_rec_dt),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(acs_rghts_exprtn_dt / 1000) as acs_rghts_exprtn_dt,
        to_timestamp(auth_dt / 1000) as auth_dt,
        to_timestamp(title_rec_dt / 1000) as title_rec_dt
    from {{ raw_or_empty(
        source('blm', 'raw_blm__blm_public_lands_access_lines'),
        [
            'globalid',
            'geometry',
            'geo_name',
            'acs_rghts_exprtn_dt:bigint',
            'auth_dt:bigint',
            'title_rec_dt:bigint',
        ]
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'blm_public_lands_access_lines'",
            'globalid',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
