-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The alaska_trails/ folder's places layers, conformed to
-- int_places__unioned's columns: each layer's rename to the union's names
-- and its key, nothing filtered (decision 40; a club's review gate is an
-- intermediate's). The layer's own columns ride whole in `properties`,
-- under dlt's names, so a rule downstream reads a field by the name its
-- registry row gives it: json_merge_patch drops a member a patch sets to
-- null, so `properties` is the base row without the geometry that travels
-- beside it.
select
    'aklt_communities' as source_key,
    'alaska_trails' as club,
    place_key,
    cast(local as varchar) as name,
    cast(type as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_alaska_trails__aklt_communities),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_alaska_trails__aklt_communities') }}
union all by name
select
    'aklt_story_map_pins' as source_key,
    'alaska_trails' as club,
    place_key,
    cast(displaytitle as varchar) as name,
    cast(pintype as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_alaska_trails__aklt_story_map_pins),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_alaska_trails__aklt_story_map_pins') }}
