-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- Friends of the Ouachita Trail: Trail Condition Report (sources.json
-- `foot_trail_condition_report`) in the shape every club notice shares
-- (int_closures__club_notices_unioned): renames and casts only. Each field
-- is read by its own name out of the row as JSON, so a field the source
-- drops or renames reads as null rather than failing every club's build.
-- The reader's shape: extract/_json_apis.py's SHEET_COLUMNS; `description`
-- and `comments` are the club's wording and stay in base.
--
-- Only facts cross from base_: the source's id, title, category, status,
-- dates, link, a place name and its own geometry (decision 55, and
-- ORG_NOTICES.md section 7). Classifying a status, holding back an ended
-- notice and placing it are int_closures__club_notices' work.
with base as (
    select *
    from {{ ref('base_ouachita__foot_trail_condition_report') }}
),

attributes as (
    select *
    from base
),

fields as (
    select
        notice_key,
        _loaded_at,
        to_json(attributes) as row_json
    from attributes
)

select
    fields.notice_key,
    'foot_trail_condition_report' as source_key,
    'ouachita' as club,
    'warnings' as notice_type,
    'sheet_csv_segments' as reader,
    'full' as listing,
    concat_ws(
        '|',
        {{ notice_field('table_title') }},
        {{ notice_field('sect') }},
        {{ notice_field('begin_mile') }},
        {{ notice_field('end_mile') }}
    ) as source_id,
    {{ notice_field('sect') }} as title,
    {{ notice_field('table_title') }} as category,
    cast(null as varchar) as status,
    cast(null as timestamptz) as starts_at,
    cast(null as timestamptz) as ends_at,
    cast(null as timestamptz) as rescinded_at,
    {{ notice_instant(notice_field('report_date')) }} as source_edited_at,
    cast(null as varchar) as source_url,
    {{ notice_field('ranger_district') }} as locality,
    cast(null as varchar) as geom_geojson,
    fields._loaded_at
from fields
