-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- MRATC Suggested Hikes in the Mt. Rogers Area (mratc.org/suggested-hikes)
-- (MRATC, sources.json `mratc_suggested_hikes`): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. A base
-- model, the one place this dataset is staged (decision 34).
--
-- Key: The kind of hike and its name (`section`, `name`): unique on all 7
-- rows read 2026-10-04; the names alone are too, but the page numbers hikes
-- within each kind, so the pair is what the page itself keeps apart.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('mratc', 'raw_mratc__mratc_suggested_hikes'),
        ['section', 'name', 'link']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'mratc_suggested_hikes'",
            'section',
            'name',
        ]) }} as hike_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='hike_key', order_by='_dlt_id'
) }}
