-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- TEHCC club wiki: hike pages (Template:Hike) (TEHCC, sources.json
-- `tehcc_wiki_hikes`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: `pageid`: unique on all 52 pages read 2026-10-04 (titles unique
-- too), the wiki's own page id, which a page keeps through edits and
-- renames.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('tehcc', 'raw_tehcc__tehcc_wiki_hikes'),
        ['pageid', 'title', 'fullurl']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'tehcc_wiki_hikes'",
            'pageid',
        ]) }} as hike_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='hike_key', order_by='_dlt_id'
) }}
