"""Real `dbt source freshness` runs on the notice sources, against a warehouse that holds only their run log.

Decision 100 (the maintainer's poll of 2026-10-07, on round-2 finding ARC-5:
"Red after 24h. But this should be Red in the data source freshness feature of
dbt. Not blocking a datasource pipeline"): a notice source the extract cannot
read stays a warning on the extract run, and dbt's source freshness turns red
once that source has gone 24 hours without being read or confirmed unchanged.

THE TRAP THIS HOLDS. `_loaded_at` is stamped only when a resource runs, so a
source whose change check answers FRESH keeps its last load's stamp (the dlt
skill, "the rest of .dlt configuration"). Measured on `_loaded_at`, every quiet,
healthy source would read as days old, and a 24-hour error on it would turn
them all red. So every notice source measures from the extract's run log
instead (macros/last_read_or_confirmed_at.sql): the newest `_extract_runs` row
for its table whose outcome is `loaded` or `skipped`, which a refused run never
writes. A source with no such row counts from the first row the log holds for
it, the first time the extract asked.

The warehouse here is built by hand: `raw._extract_runs` with the rows each
case needs, and each case's raw table with the `_loaded_at` its last load gave
it. Freshness runs only queries, so nothing else is needed. The sources are
picked from the generated sources YAML by what they are (cadence, and
`reaches_hikers` on their sources.json row), so no case rests on one club
staying registered. The YAML, not generate_notice_models.py's own list, because
that list imports every club's resource module and so dlt, which the dbt job's
pipeline venv does not hold.

It needs dbt 2.0.6 with the packages under pipeline/dbt/dbt_packages/, and
the generated models (generate_dbt.py), and runs only when OURHIKE_DBT names
that dbt: pipeline-tests.yml's dbt job and scripts/test.sh's dbt suite set it.
"""

from __future__ import annotations

import csv
import json
import os
import subprocess
from datetime import UTC, datetime, timedelta
from pathlib import Path

import duckdb
import pytest
import yaml

PIPELINE_DIR = Path(__file__).resolve().parent.parent
DBT_DIR = PIPELINE_DIR / "dbt"
#: The first line of every file generate_notice_models.py writes (its MARKER).
GENERATED = "# GENERATED by pipeline/generate_notice_models.py"
DBT = os.environ.get("OURHIKE_DBT")
pytestmark = pytest.mark.skipif(not DBT, reason="OURHIKE_DBT names no dbt (the dbt job and scripts/test.sh set it)")

NOW = datetime.now(UTC).replace(microsecond=0)


def _ago(hours: float) -> datetime:
    return NOW - timedelta(hours=hours)


def _generated_notice_tables() -> list[tuple[str, dict]]:
    """(dbt source name, table) of every generated notice source, from the generated sources YAML."""
    found = []
    for path in sorted(DBT_DIR.glob("models/staging/*/notices/_*__sources.yml")):
        text = path.read_text(encoding="utf-8")
        if not text.startswith(GENERATED):
            continue
        for source in yaml.safe_load(text)["sources"]:
            found.extend((source["name"], table) for table in source["tables"])
    return found


def _pdf_notice_tables() -> set[str]:
    """The raw table of every PDF notice: a page notice whose sources.json URL is a PDF, as generate_notice_models.py's
    is_pdf_notice() decides it, read here from the readers seed and the registry because the generator imports dlt.
    tests/test_generated_notice_models.py holds the generator's own list to the same tables."""
    registry = {row["key"]: row for row in json.loads((PIPELINE_DIR / "sources.json").read_text())["sources"]}
    with (DBT_DIR / "seeds" / "notice_readers.csv").open(newline="") as handle:
        return {
            row["raw_table"]
            for row in csv.DictReader(handle)
            if row["reader"] == "page_notice" and str(registry.get(row["source_key"], {}).get("url", "")).lower().endswith(".pdf")
        }


def _notice_sources(cadence: str, reaches_hikers: bool, count: int) -> list[tuple[str, str]]:
    """(dbt source name, raw table) of the first `count` generated notice sources of `cadence`, PDF notices left out
    (test_publish_conditions_freshness_measures_every_pdf_notice has them), whose sources.json row does or does not
    say reaches_hikers false."""
    with (DBT_DIR / "seeds" / "notice_readers.csv").open(newline="") as handle:
        keys = {row["raw_table"]: row["source_key"] for row in csv.DictReader(handle)}
    registry = {row["key"]: row for row in json.loads((PIPELINE_DIR / "sources.json").read_text())["sources"]}
    pdfs = _pdf_notice_tables()
    found = []
    for source_name, table in _generated_notice_tables():
        config = table.get("config") or {}
        quiet = registry.get(keys.get(table["name"]), {}).get("reaches_hikers") is False
        if config.get("meta", {}).get("cadence") == cadence and table["name"] not in pdfs:
            if quiet is not reaches_hikers:
                found.append((source_name, table["name"]))
    assert len(found) >= count, f"fewer than {count} {cadence} notice sources with reaches_hikers {reaches_hikers}"
    return found[:count]


def _cases() -> dict[str, tuple[str, str, datetime, list[tuple[str, datetime]]]]:
    """Each case: (dbt source name, raw table, its `_loaded_at`, its run log rows as (outcome, checked_at))."""
    hourly = _notice_sources("hourly", True, 5)
    daily = _notice_sources("daily", True, 2)
    (quiet,) = _notice_sources("hourly", False, 1)
    every_4_hours = range(26, 0, -4)  # the notices job's cron, decision 61: 26, 22, ..., 2 hours ago
    cases = {
        "refused for 30 hours": (hourly[0], _ago(30), [("loaded", _ago(30)), *(("refused", _ago(h)) for h in every_4_hours)]),
        "confirmed unchanged an hour ago": (
            hourly[1],
            _ago(7 * 24 + 1),
            [("loaded", _ago(7 * 24 + 1)), *(("skipped", _ago(h)) for h in range(7 * 24 - 3, 0, -4))],
        ),
        "read an hour ago": (hourly[2], _ago(1), [("loaded", _ago(1))]),
        "never read, first asked 30 hours ago": (hourly[3], None, [("refused", _ago(30)), ("incomplete", _ago(6))]),
        "never read, first asked 2 hours ago": (hourly[4], None, [("refused", _ago(2))]),
        "daily, confirmed 30 hours ago": (daily[0], _ago(80), [("loaded", _ago(80)), ("skipped", _ago(30))]),
        "daily, refused for 50 hours": (daily[1], _ago(50), [("loaded", _ago(50)), ("refused", _ago(26)), ("refused", _ago(2))]),
        "reaching no hiker, refused for 30 hours": (quiet, _ago(30), [("loaded", _ago(30)), ("refused", _ago(2))]),
    }
    built = {name: (*source, loaded_at, rows) for name, (source, loaded_at, rows) in cases.items()}
    # The conditions job's own upstream, hand-staged: NWS's alerts, refused on the last three hourly reads, which
    # decision 101's 2 hours turn red where every other source this leg reads would still pass.
    built["NWS's alerts, refused for 3 hours"] = (
        "nws",
        "raw_nws__alerts",
        _ago(3),
        [("loaded", _ago(3)), *(("refused", _ago(h)) for h in range(2, 0, -1))],
    )
    return built


@pytest.fixture(scope="module")
def freshness(tmp_path_factory) -> dict[str, str]:
    """{case: the status `dbt source freshness` gave its source}, from one run over every case's source."""
    root = tmp_path_factory.mktemp("notice_freshness")
    warehouse = root / "warehouse.duckdb"
    cases = _cases()
    with duckdb.connect(str(warehouse)) as con:
        con.execute("create schema raw")
        con.execute(
            "create table raw._extract_runs (run_id varchar, pipeline varchar, table_name varchar, "
            "resource_name varchar, verdict varchar, outcome varchar, checked_at timestamptz)"
        )
        for _source, table, loaded_at, rows in cases.values():
            # A table never loaded is created empty from its hints (extract/_warehouse.py's not_yet_loaded()).
            con.execute(
                f'create table raw."{table}" as select 1 as id, ?::timestamptz as _loaded_at where ? is not null',
                [loaded_at, loaded_at],
            )
            for outcome, checked_at in rows:
                con.execute(
                    "insert into raw._extract_runs values (?, 'notices_ua', ?, ?, ?, ?, ?)",
                    [
                        checked_at.strftime("%Y%m%dT%H%M%S.%fZ"),
                        table,
                        table.removeprefix("raw_"),
                        "fresh" if outcome == "skipped" else "stale",
                        outcome,
                        checked_at,
                    ],
                )
    selection = [f"source:{source}.{table}" for source, table, _loaded_at, _rows in cases.values()]
    completed, by_id = _dbt_source_freshness(root, warehouse, "--select", *selection)
    statuses = {
        name: by_id.get(f"source.ourhike.{source}.{table}", "not measured")
        for name, (source, table, _loaded_at, _rows) in cases.items()
    }
    print(completed.stdout[-6000:])
    # dbt exits 1 when any source errors and 0 when the worst is a warning (measured on 2.0.6, 2026-10-07).
    assert completed.returncode == (1 if "error" in statuses.values() else 0), completed.stdout[-3000:]
    return statuses


def _dbt_source_freshness(root: Path, warehouse: Path, *selection: str) -> tuple[subprocess.CompletedProcess, dict]:
    """`dbt source freshness` over `warehouse` with `selection`, and {unique_id: status} of every source it measured."""
    env = {
        **os.environ,
        "OURHIKE_WAREHOUSE": str(warehouse),
        "OURHIKE_PROCESSED_DIR": str(root / "processed"),
        "DBT_ENGINE_SEND_ANONYMOUS_USAGE_STATS": "false",
    }
    completed = subprocess.run(
        [
            DBT,
            "source",
            "freshness",
            "--profiles-dir",
            ".",
            "--target-path",
            str(root / "target"),
            "--log-path",
            str(root / "logs"),
            *selection,
        ],
        cwd=DBT_DIR,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    results_path = root / "target" / "sources.json"
    assert results_path.exists(), completed.stdout[-4000:] + completed.stderr[-2000:]
    results = json.loads(results_path.read_text())["results"]
    return completed, {result["unique_id"]: result["status"].lower() for result in results}


@pytest.fixture(scope="module")
def publish_conditions_selection(tmp_path_factory) -> dict[str, str]:
    """{source.table: status} of every PDF notice, from `dbt source freshness` with publish-conditions.yml's own
    selection after the build read a notices copy (`tag:conditions_job tag:notices_job`, no exclude), over a warehouse
    whose run log holds only each PDF's one refused read 30 hours ago. No raw table exists for any of them, as for a
    PDF the extract has never read: the run log is all freshness reads (macros/last_read_or_confirmed_at.sql)."""
    root = tmp_path_factory.mktemp("pdf_notice_freshness")
    warehouse = root / "warehouse.duckdb"
    pdfs = {
        f"{source_name}.{table['name']}": table["name"]
        for source_name, table in _generated_notice_tables()
        if table["name"] in _pdf_notice_tables()
    }
    assert len(pdfs) >= 4, f"the four PDF notices of 2026-10-09 are not all generated: {sorted(pdfs)}"
    with duckdb.connect(str(warehouse)) as con:
        con.execute("create schema raw")
        con.execute(
            "create table raw._extract_runs (run_id varchar, pipeline varchar, table_name varchar, "
            "resource_name varchar, verdict varchar, outcome varchar, checked_at timestamptz)"
        )
        for table in pdfs.values():
            con.execute(
                "insert into raw._extract_runs values (?, 'notices_ua', ?, ?, 'stale', 'refused', ?)",
                [_ago(30).strftime("%Y%m%dT%H%M%S.%fZ"), table, table.removeprefix("raw_"), _ago(30)],
            )
    completed, by_id = _dbt_source_freshness(root, warehouse, "--select", "tag:conditions_job", "tag:notices_job")
    print(completed.stdout[-6000:])
    return {name: by_id.get(f"source.ourhike.{name}", "not measured") for name in pdfs}


def test_publish_conditions_freshness_measures_every_pdf_notice_and_one_unread_for_30_hours_is_red(
    publish_conditions_selection,
):
    """The review of PR #1805 (dlt → dbt re-platform as one go/no-go change), 2026-10-09: the four PDF notices, each
    reaching hikers, carried no freshness, and dbt 2.0.6 leaves a source with no thresholds out of `source freshness`
    without a word, so a PDF the extract stopped reading kept publishing its last table and nothing turned red.
    Production's command measures them now; CI's two leave them out by generate_notice_models.py's PDF_NOTICE_TAG,
    because fixture mode lands no PDF (tests/test_generated_notice_models.py holds the three commands)."""
    assert publish_conditions_selection == dict.fromkeys(publish_conditions_selection, "error")


def test_a_notice_source_refused_for_over_24_hours_is_stale(freshness):
    assert freshness["refused for 30 hours"] == "error"


def test_a_notice_source_confirmed_unchanged_an_hour_ago_is_fresh_though_its_loaded_at_is_a_week_old(freshness):
    """The trap: FRESH reloads nothing, so `_loaded_at` stays at the load a week ago while every check since passed."""
    assert freshness["confirmed unchanged an hour ago"] == "pass"


def test_a_notice_source_read_an_hour_ago_is_fresh(freshness):
    assert freshness["read an hour ago"] == "pass"


def test_a_notice_source_never_read_since_the_extract_first_asked_30_hours_ago_is_stale(freshness):
    """No `loaded` or `skipped` row at all: counted from the first row the log holds, not read as 1970 or as now."""
    assert freshness["never read, first asked 30 hours ago"] == "error"


def test_a_notice_source_the_extract_first_asked_2_hours_ago_is_not_stale_yet(freshness):
    """A source registered this morning has not gone 24 hours unread, whatever its first read answered."""
    assert freshness["never read, first asked 2 hours ago"] == "pass"


def test_a_daily_notice_source_confirmed_30_hours_ago_is_not_stale_because_it_is_checked_once_a_day(freshness):
    """extract/_run.py's due() leaves a daily resource out until its last good check is 24 hours old, and a run that
    leaves it out logs no row, so a healthy one is routinely more than 24 hours past its last row."""
    assert freshness["daily, confirmed 30 hours ago"] == "pass"


def test_a_daily_notice_source_refused_for_50_hours_is_stale(freshness):
    assert freshness["daily, refused for 50 hours"] == "error"


def test_a_refused_source_that_reaches_no_hiker_only_warns(freshness):
    """extract/_run.py's quiet_refusals(): a source whose sources.json row says reaches_hikers false is held to a
    warning on the extract run, and to one here."""
    assert freshness["reaching no hiker, refused for 30 hours"] == "warn"


def test_nws_alerts_refused_for_3_hours_are_stale(freshness):
    """The conditions job's own upstreams, refused on their own, warn on the hourly run as the notices job's do
    (decision 101), and NWS's alerts are red here after 2 hours unread, not 24 (the maintainer's poll of 2026-10-07:
    "Both, NWS red after 2 h")."""
    assert freshness["NWS's alerts, refused for 3 hours"] == "error"
