-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- City of Duluth parks (City of Duluth, sources.json
-- `duluth_park_boundaries`): every row, keyed and deduped (decision 40),
-- with nothing filtered and nothing joined. A base model, the one place
-- this dataset is staged (decision 34).
--
-- Key: `GlobalID` is unique and non-null on all 165 rows read 2026-10-03.
--
-- Dates: created_data, last_edited_date, the layer's esriFieldTypeDate
-- fields (sources.json `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, created_data, last_edited_date),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(created_data / 1000) as created_data,
        to_timestamp(last_edited_date / 1000) as last_edited_date
    from {{ raw_or_empty(
        source('duluth', 'raw_duluth__duluth_park_boundaries'),
        [
            'globalid',
            'geometry',
            'park_name',
            'created_data:bigint',
            'last_edited_date:bigint',
        ]
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'duluth_park_boundaries'",
            'globalid',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
