-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- FWS National Wildlife Refuge public hunt units (sources.json
-- `fws_hunt_units`, landed by extract/usfws/warnings.py's ArcgisLayer):
-- every row, keyed and deduped (decision 40), with nothing filtered and
-- nothing joined. Its words, prose included, stay here: the staging model
-- beside it carries only facts (decision 55).
--
-- Key: globalid. Measured: Read by this step at 2026-10-03T16:08:29Z:
-- returnCountOnly under the row's `where` answered 2215, and `GlobalID` is
-- distinct on 2215 of them (returnDistinctValues), the key phase C builds
-- on.
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ notice_raw_table(
        source('usfws', 'raw_usfws__fws_hunt_units'),
        ['geometry', 'globalid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'fws_hunt_units'",
            'globalid',
        ]) }} as notice_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
