-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- NC High Peaks trails: the Black Mountains' USFS, state park and MST
-- trails (the association's KML) (NCHPTA, sources.json `nchpta_trails`):
-- every row, keyed and deduped (decision 40), with nothing filtered and
-- nothing joined. A base model, the one place this dataset is staged
-- (decision 34).
--
-- Key: The geometry alone: unique on 28 of 28 (measured 2026-10-04). `name`
-- is also unique.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('nc_high_peaks', 'raw_nc_high_peaks__nchpta_trails') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nchpta_trails'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
