-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The pcta/ folder's places layers, conformed to int_places__unioned's
-- columns: each layer's rename to the union's names and its key, nothing
-- filtered (decision 40; a club's review gate is an intermediate's). The
-- layer's own columns ride whole in `properties`, under dlt's names, so a
-- rule downstream reads a field by the name its registry row gives it:
-- json_merge_patch drops a member a patch sets to null, so `properties` is
-- the base row without the geometry that travels beside it.
select
    'pcta_centerline_regions' as source_key,
    'pcta' as club,
    place_key,
    cast(pcta_region as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_pcta__pcta_centerline_regions),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_pcta__pcta_centerline_regions') }}
union all by name
select
    'pcta_letter_sections' as source_key,
    'pcta' as club,
    place_key,
    cast(section_name as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_pcta__pcta_letter_sections),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_pcta__pcta_letter_sections') }}
union all by name
select
    'pcta_permit_areas' as source_key,
    'pcta' as club,
    place_key,
    cast(permit_area_name as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_pcta__pcta_permit_areas),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_pcta__pcta_permit_areas') }}
union all by name
select
    'pcta_sheriffs_offices' as source_key,
    'pcta' as club,
    place_key,
    cast(sheriff_dept as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_pcta__pcta_sheriffs_offices),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_pcta__pcta_sheriffs_offices') }}
union all by name
select
    'pcta_trail_towns' as source_key,
    'pcta' as club,
    place_key,
    cast(location as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_pcta__pcta_trail_towns),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_pcta__pcta_trail_towns') }}
union all by name
select
    'pcta_wilderness_areas' as source_key,
    'pcta' as club,
    place_key,
    cast(name as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_pcta__pcta_wilderness_areas),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_pcta__pcta_wilderness_areas') }}
