-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Ozark Highlands Trail major trailheads (OHTA's trail page) (OHTA,
-- sources.json `ohta_major_trailheads`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: (`segment`, `name`): unique on 41 of 41 (measured 2026-10-04 on the
-- live REST answer, parsed as extract/_pages_points.py parses it). `name`
-- alone is 38 of 41: Woolum ford, Spring Creek and Matney Knob end one
-- segment and start the next, and are listed under both.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('ohta', 'raw_ohta__ohta_major_trailheads'),
        ['segment', 'name', 'geometry']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ohta_major_trailheads'",
            'segment',
            'name',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
