-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- OHTA Website Track: the Ozark Highlands Trail's five sections (Google My
-- Map) (OHTA, sources.json `ohta_website_track`): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. A base
-- model, the one place this dataset is staged (decision 34).
--
-- Key: The geometry alone: unique on 5 of 5 (measured 2026-10-04 on the
-- live export). `name` is also unique.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('ohta', 'raw_ohta__ohta_website_track') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ohta_website_track'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
