-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The cotrex/ folder's points of interest layers, conformed to
-- int_points_of_interest__club_unioned's columns: each layer's rename to
-- the union's names and its key, nothing filtered (decision 40; a club's
-- review gate is an intermediate's). The layer's own columns ride whole in
-- `properties`, under dlt's names, so a rule downstream reads a field by
-- the name its registry row gives it: json_merge_patch drops a member a
-- patch sets to null, so `properties` is the base row without the geometry
-- that travels beside it.
select
    'cotrex_trailheads' as source_key,
    'cotrex' as club,
    poi_key,
    cast(name as varchar) as name,
    cast(type as varchar) as category,
    cast(feature_id as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_cotrex__cotrex_trailheads),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_cotrex__cotrex_trailheads') }}
union all by name
select
    'cpw_facilities' as source_key,
    'cotrex' as club,
    poi_key,
    cast(fac_name as varchar) as name,
    cast(d_fac_type as varchar) as category,
    cast(globalid_2 as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_cotrex__cpw_facilities),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_cotrex__cpw_facilities') }}
