-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The blm/ folder's trail lines layers, conformed to
-- int_trail_lines__unioned's columns: each layer's rename to the union's
-- names and its key, nothing filtered (decision 40; a club's review gate is
-- an intermediate's). The layer's own columns ride whole in `properties`,
-- under dlt's names, so a rule downstream reads a field by the name its
-- registry row gives it: json_merge_patch drops a member a patch sets to
-- null, so `properties` is the base row without the geometry that travels
-- beside it.
select
    'blm_iditarod_nht' as source_key,
    'blm' as club,
    trail_segment_key,
    cast(trailname as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_blm__blm_iditarod_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_blm__blm_iditarod_nht') }}
union all by name
select
    'blm_old_spanish_nht_alignment' as source_key,
    'blm' as club,
    trail_segment_key,
    cast(route_name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_blm__blm_old_spanish_nht_alignment),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_blm__blm_old_spanish_nht_alignment') }}
union all by name
select
    'blm_old_spanish_nht_trails' as source_key,
    'blm' as club,
    trail_segment_key,
    cast(trail_name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_blm__blm_old_spanish_nht_trails),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_blm__blm_old_spanish_nht_trails') }}
