-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- USFS Southwestern Region fire restrictions (sources.json
-- `usfs_r03_fire_restrictions`, landed by extract/usfs/warnings.py's
-- ArcgisLayer): every row, keyed and deduped (decision 40), with nothing
-- filtered and nothing joined. Its words, prose included, stay here: the
-- staging model beside it carries only facts (decision 55).
--
-- Key: objectid, a server row id, so the geometry joins it (decision 40:
-- never a server row id alone). A reload that mints the ids again reads as
-- every notice removed and added, which moves a row's dates and never its
-- presence. @unvalidated as the smallest set of current values:
-- pipeline/spike_table_keys.py on the live layer settles it. Measured: Read
-- by this step at 2026-10-03T16:06:35Z: returnCountOnly under the row's
-- `where` answered 1, and `objectid` is distinct on 1 of them
-- (returnDistinctValues), the key phase C builds on.
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ notice_raw_table(
        source('usfs', 'raw_usfs__usfs_r03_fire_restrictions'),
        ['geometry', 'objectid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'usfs_r03_fire_restrictions'",
            'objectid',
            geometry_key('geom'),
        ]) }} as notice_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
