-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- Kootenai National Forest inaccessible roads and trails (sources.json
-- `usfs_r01_kootenai_inaccessible`, landed by extract/usfs/closures.py's
-- ArcgisLayer): every row, keyed and deduped (decision 40), with nothing
-- filtered and nothing joined. Its words, prose included, stay here: the
-- staging model beside it carries only facts (decision 55).
--
-- Key: globalid. Measured: Read by this step at 2026-10-03T16:07:23Z:
-- returnCountOnly under the row's `where` answered 393, and `GlobalID` is
-- distinct on 393 of them (returnDistinctValues), the key phase C builds
-- on.
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ notice_raw_table(
        source('usfs', 'raw_usfs__usfs_r01_kootenai_inaccessible'),
        ['geometry', 'globalid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'usfs_r01_kootenai_inaccessible'",
            'globalid',
        ]) }} as notice_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
