-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Alaska Long Trail communities and places (AKLT_POI) (Alaska Trails,
-- sources.json `aklt_communities`): every row, keyed and deduped (decision
-- 40), with nothing filtered and nothing joined. A base model, the one
-- place this dataset is staged (decision 34).
--
-- Key: `Local` is unique and non-null on all 42 rows read 2026-10-03.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('alaska_trails', 'raw_alaska_trails__aklt_communities') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'aklt_communities'",
            'local',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
