-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The usfws/ folder's points of interest layers, conformed to
-- int_points_of_interest__club_unioned's columns: each layer's rename to
-- the union's names and its key, nothing filtered (decision 40; a club's
-- review gate is an intermediate's). The layer's own columns ride whole in
-- `properties`, under dlt's names, so a rule downstream reads a field by
-- the name its registry row gives it: json_merge_patch drops a member a
-- patch sets to null, so `properties` is the base row without the geometry
-- that travels beside it.
select
    'usfws_refuge_access_points' as source_key,
    'usfws' as club,
    poi_key,
    cast(gate_name as varchar) as name,
    cast(acc_type as varchar) as category,
    cast(globalid as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_usfws__usfws_refuge_access_points),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_usfws__usfws_refuge_access_points') }}
union all by name
select
    'usfws_refuge_property_points' as source_key,
    'usfws' as club,
    poi_key,
    cast(prop_name as varchar) as name,
    cast(prop_type as varchar) as category,
    cast(globalid as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_usfws__usfws_refuge_property_points),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_usfws__usfws_refuge_property_points') }}
