"""Great Western Trail Association: closures, drawn from another folder's resource (decision 53 phase
B, 2026-10-03).

This club's closures arrive through usfs/ `usfs_r04_forest_orders`, each extracted once in its
steward's folder (decision 34). Its portion is assigned in dbt.

Before decision 53 phase B, 2026-10-03, this note read:

Great Western Trail Association: closures, published, and not landed (coverage audit 2026-10-01,
batch p01_persist).

Licence: open_licence, public domain (federal work, 17 U.S.C. §105) for both USFS services. R4
copyrightText: "USDA Forest Service Intermountain Region - Information Management GIS. Original
workflows generated by USDA FS Forest Service Southwest Region." R3: "The USDA Forest Service makes
no …

Restated from reference/org_coverage.json, whose text is trimmed where it ends in '…'.
"""

from datetime import date

from extract._contract import NotAvailable

NOT_AVAILABLE = NotAvailable(
    confirmed=date(2026, 10, 3),
    checked=(
        "via usfs/ `usfs_r04_forest_orders` (decision 53 phase B, 2026-10-03): `usfs_r04_forest_orders` reads `R04_Forest_Orders_PUBLIC_VIEW/FeatureServer/0`",
        'USFS Intermountain Region (R4): `https://apps.fs.usda.gov/fsgisx02/rest/services/r04/R04_Alerts_And_Closures_01/MapServer/0` "ForestOrder". 230 polygons; max `pub_date` 2026-10-01, max `signeddate` 2026-09-21.',
        "By forest: Uinta-Wasatch-Cache 96, Bridger-Teton 33, Payette 23, Caribou-Targhee 17, Boise 15, Humboldt-Toiyabe 11, Dixie 10, Salmon-Challis 9, Fishlake 7, Sawtooth 5, Manti-La Sal 3.",
        "By `ordertype`: Safety Closure 77, Recreation Restriction 52, Closure for Resource Protection 45, Motor Vehicle Use Prohibition 24, Fire Closure - Stage 3: 3.",
        "Fields include `startdate` …",
    ),
    where=(
        "https://services1.arcgis.com/gGHDlz6USftL5Pau/arcgis/rest/services/R04_Forest_Orders_PUBLIC_VIEW/FeatureServer/0",
        "https://apps.fs.usda.gov/fsgisx02/rest/services/r04/R04_Alerts_And_Closures_01/MapServer/0",
        "https://apps.fs.usda.gov/fsgisx02/rest/services/r03/r03_ForestOrder_01/MapServer",
        "https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Fire_Restrictions/FeatureServer/0",
    ),
    reason="drawn from usfs/'s resources, extracted once there (decision 34); checked names the layers this org's data arrives in",
)
