-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- Mohonk Preserve deer management zones (sources.json `mohonk_deer_zones`,
-- landed by extract/mohonk/warnings.py's ArcgisLayer): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. Its
-- words, prose included, stay here: the staging model beside it carries
-- only facts (decision 55).
--
-- Key: globalid. Measured: Read by this step at 2026-10-03T16:11:33Z:
-- returnCountOnly under the row's `where` answered 16, and `GlobalID` is
-- distinct on 16 of them (returnDistinctValues), the key phase C builds on.
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ notice_raw_table(
        source('mohonk', 'raw_mohonk__mohonk_deer_zones'),
        ['geometry', 'globalid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'mohonk_deer_zones'",
            'globalid',
        ]) }} as notice_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
