-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Finger Lakes Trail waypoints (FLTC's own layer) (FLTC, sources.json
-- `fltc_waypoints`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: (Category, MapName, Name): 1,789 of 1,789 (measured 2026-10-04 by
-- reading every row and every vertex as the extract reads the layer
-- (f=geojson, outSR 4326), under lib/user_agent.py's USER_AGENT, robots.txt
-- first). (Name, MapName), the pair the row's notes give as the natural
-- key, is 1,788 on this read: one name repeats on one map sheet, in two
-- categories. `ViewLink` is unique alone but is the object id in a URL ('
-- https://fltmap.cc/waypoints/1004' on OBJECTID 1004), which a reload would
-- mint again; the geometry alone is 1,729 distinct (113 rows share a
-- point).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('fltc', 'raw_fltc__fltc_waypoints') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'fltc_waypoints'",
            'category',
            'mapname',
            'name',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
