-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Non-FLT trails near the Finger Lakes Trail (FLTC) (FLTC, sources.json
-- `fltc_non_flt_trails`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: the geometry (every vertex at 6 decimal places): 215 of 215, and no
-- attribute column is unique (measured 2026-10-03 over every row).
--
-- Dates: date_modif, the layer's esriFieldTypeDate fields (sources.json
-- `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, date_modif),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(date_modif / 1000) as date_modif
    from {{ raw_or_empty(
        source('fltc', 'raw_fltc__fltc_non_flt_trails'),
        ['geometry', 'label', 'date_modif:bigint']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'fltc_non_flt_trails'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
