-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Superior Hiking Trail spurs and loops, 2025 (SHTA) (SHTA, sources.json
-- `shta_spurs_and_loops`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: the geometry (every vertex at 6 decimal places): 181 of 181 after 1
-- exact copy, no attribute being unique (measured 2026-10-03 over every
-- row).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('shta', 'raw_shta__shta_spurs_and_loops') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'shta_spurs_and_loops'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
