-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- OCVT's A.T. section tracks, 2009 (two GPX files) (OCVT, sources.json
-- `ocvt_at_tracks`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: The geometry alone: unique on 2 of 2 (measured 2026-10-04).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('ocvt', 'raw_ocvt__ocvt_at_tracks') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ocvt_at_tracks'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
