-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- RMFI Project Map: project sites past, present and ongoing (Google My Map)
-- (RMFI, sources.json `rmfi_project_map`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: The geometry alone: unique on 46 of 46 (measured 2026-10-04 on the
-- live export). `name` is also unique.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('rmfi', 'raw_rmfi__rmfi_project_map'),
        ['geometry', 'name']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'rmfi_project_map'",
            geometry_key('geom'),
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
