"""Write the dbt staging layer for the clubs' registered ArcGIS layers from the registry, and check it.

pipeline/ELT.md, "Loading everything the clubs publish (decision 54)": "dbt models are generated, not
hand-written, wherever a layer has a measured key: a `base_<folder>__<key>` per raw table from one template,
keyed and deduped on the key the live read found, and each mart's union reading the registry for its
branches." This is that template. Its output is committed, and tests/test_dbt_generated_staging.py fails when a
committed file differs from what this would write, so a registry edit and its models land together.

    python make_dbt_staging.py           write every generated file, and delete a generated file it no longer writes
    python make_dbt_staging.py --check   write nothing; exit 1 naming each file that would change

WHICH LAYERS (registry-driven, by kind, type and measured key). Every resource that a club folder's file for
one of TYPES extracts as an ArcGIS layer (extract/_kinds.py's ArcgisLayer, a sources.json row of a kind in
KINDS), unless a hand-written model already reads its raw table: those keep their own (the registry tables
staged before decision 54). So a layer registered later is staged by running this again, and by nothing else.

WHAT EACH sources.json ROW GIVES IT:
- THE KEY (decision 40): `key_fields`, else `id_fields`, else `id_field`, where `geometry` in a list stands for
  the shape (macros/geometry_key.sql) and an empty `key_fields` is a one-row layer, keyed by the registry key
  and its shape (base_pcta__centerline's precedent: a key needs a column beside the registry key). A row with
  none of these, or whose key holds a server's row id (OBJECTID, FID: a reload mints them again), STOPS the
  run and is named, so no table is staged without a measured key.
- `date_fields`: the layer's esriFieldTypeDate fields, which land as epoch milliseconds (extract/_kinds.py's
  ESRI_TYPES, "the base model converts them") and are cast to timestamptz here, in UTC as ArcGIS stores them.
  A row without it has its dates, if it has any, left as the integers dlt landed.
- per type, the fields a staging model renames to the union's columns (SHAPES): `name_field` or
  `name_constant` and `category_field` for places, `elevation_source` for elevation.

Column names are the registry's field names as dlt names them on landing (the `sql_ci_v1` convention
.dlt/config.toml sets, path by path), quoted where DuckDB reserves the word, so `DESC_` is `"desc"`.

WHAT IT WRITES, for each club folder <f> with such layers, under dbt/models/staging/<f>/:
- `_<f>__generated__sources.yml`: each raw table, with its duplicates_are_exact test on the model's own key.
- `base/base_<f>__<key>.sql` and `base/_<f>__generated__base.yml`: one base model per raw table.
- `stg_<f>__<type>.sql` and `_<f>__generated__models.yml`: one staging model per type, every layer of that
  type in the folder conformed to its union's columns, the layer's own columns kept whole as `properties`.
And per type, under dbt/models/intermediate/<type>/: `int_<type>__unioned.sql` and its YAML, a `union all by
name` of every staging model this writes for the type. And `dbt/macros/generated_regions.sql`, the region box
each generated source's rows are held to (macros/lands_outside_its_region.sql).

Every file it writes opens with GENERATED, which is how it knows which files are its own.
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap
from dataclasses import dataclass
from functools import cache
from pathlib import Path

PIPELINE = Path(__file__).resolve().parent
DBT = PIPELINE / "dbt"
MODELS = DBT / "models"
STAGING = MODELS / "staging"
INTERMEDIATE = MODELS / "intermediate"
REGIONS_MACRO = DBT / "macros" / "generated_regions.sql"

GENERATED = "GENERATED by pipeline/make_dbt_staging.py"
SQL_MARK = f"-- {GENERATED} from sources.json\n-- and the extract's club folders; edit them or it, never this file.\n"
YAML_MARK = f"# {GENERATED} from sources.json\n# and the extract's club folders; edit them or it, never this file.\n"
JINJA_MARK = f"{{#- {GENERATED} from sources.json\n    and the extract's club folders; edit them or it, never this file. -#}}\n"

#: The registry kinds an ArcgisLayer reads.
KINDS = ("club_arcgis_layer", "external_arcgis_layer")

#: The server row ids a key may never hold (decision 40: a truncate-and-reload mints them again), as dlt names them.
ROW_IDS = frozenset({"objectid", "objectid_1", "objectid_12", "fid", "oid", "esri_oid", "ogc_fid"})

#: The region every generated source's rows are held to. The widest of the three boxes
#: macros/lands_outside_its_region.sql draws, and still one that catches a swapped United States point (its
#: latitude would read -64 or less). @unvalidated as a fit: no generated layer's vertices had been read when
#: this was set, and a server's own extent is never the evidence (ELT.md, "What wave 1's live reads found":
#: USFWS's answered lat -24.99 to 90 for vertices at 13.64 to 63.20). What settles each is its row of
#: int_<type>__source_extents on a live build, which names the narrowest box its vertices fit.
DEFAULT_REGION = "us_and_territories"

LINE = 76  # SQL comment width: SQLFluff's LT05 holds every line to 80


@dataclass(frozen=True)
class Shape:
    """What one type's staging models conform to, and the union that reads them."""

    key_column: str  # <what one row is>_key (decision 40)
    row: str  # what one row is, in words
    union: str
    columns: tuple[tuple[str, str], ...]  # (column, description) beside the key, source_key, club, geom, properties, _loaded_at


SHAPES = {
    "places": Shape(
        key_column="place_key",
        row="one feature of a places layer: a park, a public land unit, a town, a section of trail",
        union="int_places__unioned",
        columns=(
            (
                "name",
                "The layer's own name for the feature, from the registry's `name_field`, or its `name_constant` for a layer that names its one feature only in the registry; null where it has neither.",
            ),
            ("category", "The layer's own category, from the registry's `category_field`; null where the registry names none."),
        ),
    ),
    "elevation": Shape(
        key_column="elevation_feature_key",
        row="one feature of an elevation layer: a point with a height, a line whose vertices carry one, or a band",
        union="int_elevation__unioned",
        columns=(
            (
                "published_elevation",
                "The elevation field the registry's `elevation_source` names (`field <name>`), as text, exactly as the layer publishes it; null for a layer whose elevation is its geometry's Z. Its unit is the registry's `elevation_unit`, which int_elevation__club_samples reads row by row.",
            ),
        ),
    ),
}


class KeyRefused(ValueError):
    """A registry row with no usable measured key: the run stops and names it."""


@cache
def _naming():
    from dlt.common.normalizers.naming.sql_ci_v1 import NamingConvention

    return NamingConvention()


@cache
def _reserved() -> frozenset[str]:
    import duckdb

    rows = duckdb.sql("select keyword_name from duckdb_keywords() where keyword_category in ('reserved', 'type_function')")
    return frozenset(name for (name,) in rows.fetchall())


def column(field: str) -> str:
    """A registry field name as the landed column: dlt's name for it, quoted where DuckDB reserves the word."""
    name = _naming().normalize_path(field)
    return f'"{name}"' if name in _reserved() else name


def _sql_text(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


@dataclass(frozen=True)
class Table:
    folder: str
    type: str
    key: str
    table: str
    cadence: str
    entry: dict

    @property
    def shape(self) -> Shape:
        return SHAPES[self.type]

    @property
    def base(self) -> str:
        return f"base_{self.folder}__{self.key}"

    @property
    def title(self) -> str:
        return self.entry.get("title") or self.key

    def key_inputs(self) -> list[str]:
        """The key's inputs as generate_surrogate_key takes them: the registry key, then each measured field."""
        entry = self.entry
        if "key_fields" in entry:
            fields, home = list(entry["key_fields"]), "key_fields"
        elif entry.get("id_fields"):
            fields, home = list(entry["id_fields"]), "id_fields"
        elif entry.get("id_field"):
            fields, home = [entry["id_field"]], "id_field"
        else:
            raise KeyRefused(f"{self.key}: no key_fields, id_fields or id_field on its sources.json row")
        if not fields:
            fields = ["geometry"]  # a one-row layer: the registry key and its shape
        inputs = [f"'{self.key}'"]
        for field in fields:
            if field == "geometry":
                inputs.append("geometry_key('geom')")
                continue
            if not isinstance(field, str) or " " in field:
                raise KeyRefused(f"{self.key}: {home} holds {field!r}, which is not one of the layer's fields")
            name = column(field)
            if name.strip('"') in ROW_IDS:
                raise KeyRefused(f"{self.key}: {home} holds {field}, a server row id, which a reload mints again (decision 40)")
            inputs.append(name)
        return inputs

    def key_comment(self) -> str:
        entry = self.entry
        text = entry.get("key_comment") or entry.get("id_comment")
        if text:
            return text
        home = "key_fields" if "key_fields" in entry else "id_fields" if entry.get("id_fields") else "id_field"
        return f"the registry's `{home}`; its row records no measurement of it."

    def date_columns(self) -> list[str]:
        return [column(field) for field in self.entry.get("date_fields") or []]


def _raw_key_columns(inputs: list[str]) -> list[str]:
    """The same key over the raw table, as duplicates_are_exact takes it: geometry_key('geom') written out."""
    raw_geometry = "md5(st_astext(st_geomfromgeojson(cast(geometry as varchar))))"
    return [raw_geometry if item == "geometry_key('geom')" else item for item in inputs]


def _hand_written_raw_tables() -> set[str]:
    """Every raw table a model this generator did not write already reads."""
    import re

    pattern = re.compile(r"source\('[a-z0-9_]+',\s*'(raw_[a-z0-9_]+)'\)")
    found = set()
    for path in MODELS.rglob("*.sql"):
        text = path.read_text()
        if GENERATED in text.split("\n", 1)[0]:
            continue
        found.update(pattern.findall(text))
    return found


def tables() -> list[Table]:
    """Every layer this stages, sorted by folder and key; stops on the first row with no usable key."""
    sys.path.insert(0, str(PIPELINE))
    from extract._contract import discover
    from extract._kinds import ArcgisLayer

    hand_written = _hand_written_raw_tables()
    found = []
    for club_file in discover():
        if club_file.type not in SHAPES:
            continue
        for resource in club_file.resources:
            if not isinstance(resource, ArcgisLayer) or resource.table in hand_written:
                continue
            entry = resource.entry
            if entry.get("kind") not in KINDS:
                continue
            found.append(Table(club_file.club, club_file.type, resource.key, resource.table, resource.cadence, entry))
    found.sort(key=lambda table: (table.folder, table.key))
    refused = []
    for table in found:
        try:
            table.key_inputs()
        except KeyRefused as error:
            refused.append(str(error))
    if refused:
        raise KeyRefused("no staging without a measured key (decision 40):\n  " + "\n  ".join(refused))
    return found


def _comment(text: str, indent: str = "") -> str:
    return "\n".join(textwrap.wrap(text, LINE - len(indent), initial_indent=f"{indent}-- ", subsequent_indent=f"{indent}-- "))


def _folded(text: str, indent: int) -> str:
    """A YAML folded scalar's body, wrapped."""
    pad = " " * indent
    return "\n".join(textwrap.wrap(text, 100 - indent, initial_indent=pad, subsequent_indent=pad))


def _held_back(entry: dict) -> str:
    if entry.get("reaches_hikers") is False:
        return "Its sources.json row reads `reaches_hikers: false`, so int_sources__publication holds it back from every mart."
    return "Whether it may publish is int_sources__publication's to decide, from its sources.json row."


# --- base models ----------------------------------------------------------------------------------------------


def _key_item(item: str) -> str:
    """One generate_surrogate_key input as the base models write it: the registry key as `"'<key>'"`, the
    geometry as the geometry_key('geom') call, and a column as a quoted string (tests/test_dbt_keys.py reads
    the list back with ast.literal_eval)."""
    if item.startswith("'"):
        return json.dumps(item)
    if item == "geometry_key('geom')":
        return item
    return repr(item)


def base_sql(table: Table) -> str:
    inputs = table.key_inputs()
    dates = table.date_columns()
    head = [
        _comment(
            f"{table.title} ({table.entry.get('provider') or table.folder}, sources.json `{table.key}`): every row, "
            "keyed and deduped (decision 40), with nothing filtered and nothing joined. A base model, the one place "
            "this dataset is staged (decision 34)."
        ),
        "--",
        _comment(f"Key: {table.key_comment()}"),
    ]
    if dates:
        head += ["--", _comment(f"Dates: {', '.join(dates)}, the layer's esriFieldTypeDate fields (sources.json `date_fields`).")]
    # SQLFluff's LT05 holds every line to 80: a long exclude list or source() call breaks over lines, the
    # source() call after its first argument, where tests/test_dbt_keys.py's pattern still reads it.
    excluded = ["geometry", *dates]
    exclude = f"* exclude ({', '.join(excluded)}),"
    if len(exclude) + 8 > 80:
        exclude = "* exclude (\n" + ",\n".join(f"            {name}" for name in excluded) + "\n        ),"
    source = f"{{{{ source('{table.folder}', '{table.table}') }}}}"
    if len(source) + 9 > 80:
        source = f"{{{{ source('{table.folder}',\n        '{table.table}') }}}}"
    casts = "".join(f",\n        to_timestamp({name} / 1000) as {name}" for name in dates)
    key_lines = "".join(f"\n            {_key_item(item)}," for item in inputs)
    return (
        SQL_MARK
        + "\n".join(head)
        + f"""
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        {exclude}
        st_geomfromgeojson(cast(geometry as varchar)) as geom{casts}
    from {source}
),

renamed as (
    select
        {{{{ dbt_utils.generate_surrogate_key([{key_lines}
        ]) }}}} as {table.shape.key_column},
        source.*
    from source
)

{{{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='{table.shape.key_column}', order_by='_dlt_id'
) }}}}
"""
    )


def _yaml_list(items: list[str]) -> str:
    return "[" + ", ".join(json.dumps(item) for item in items) + "]"


def sources_yaml(folder: str, folder_tables: list[Table]) -> str:
    lines = [
        YAML_MARK + "version: 2",
        "",
        "sources:",
        f"  - name: {folder}",
        "    description: >",
        _folded(
            f"The layers sources.json registers for the extract's {folder}/ folder (pipeline/extract/{folder}/) "
            f"that pipeline/make_dbt_staging.py stages, landed as raw_{folder}__<key> and staged once each by a "
            "generated base model here. Descriptions transcribed from sources.json's titles and key notes.",
            6,
        ),
        "    schema: raw",
        "    config:",
        "      loaded_at_field: _loaded_at",
        "      meta:",
        f"        cadence: {_cadence(folder_tables)}",
        "      freshness:",
        "        # The extract's cadence, not the steward's. @unvalidated, the same",
        "        # threshold and open question as _atc__sources.yml.",
        "        warn_after: {count: 7, period: day}",
        "    tables:",
    ]
    for table in folder_tables:
        lines += [
            f"      - name: {table.table}",
            "        data_tests:",
            f"          # Rows sharing {table.base}'s key must be exact copies (decision 40).",
            "          - duplicates_are_exact:",
            "              arguments:",
            f"                key_columns: {_yaml_list(_raw_key_columns(table.key_inputs()))}",
            "        description: >",
            _folded(f"{table.title} (sources.json `{table.key}`). Key: {table.key_comment()}", 10),
        ]
    return "\n".join(lines) + "\n"


def _cadence(folder_tables: list[Table]) -> str:
    cadences = {table.cadence for table in folder_tables}
    if len(cadences) != 1:
        raise ValueError(f"{folder_tables[0].folder}: one source block per folder needs one cadence, found {sorted(cadences)}")
    return cadences.pop()


def base_yaml(folder: str, folder_tables: list[Table]) -> str:
    lines = [YAML_MARK + "version: 2", "", "models:"]
    for table in folder_tables:
        inputs = ", ".join(item.strip("'") if item.startswith("'") else item for item in table.key_inputs())
        lines += [
            f"  - name: {table.base}",
            "    data_tests:",
            "      # Says how many rows the dedupe dropped. Each is an exact copy",
            "      # (duplicates_are_exact on the raw table), so this only reports.",
            "      - dbt_utils.equal_rowcount:",
            "          arguments:",
            f"            compare_model: source('{folder}', '{table.table}')",
            "          config:",
            "            severity: warn",
            "    description: >",
            _folded(
                f"{table.title}, every row, keyed and deduped (decision 40), the layer's own columns under dlt's "
                f"names. {_held_back(table.entry)} {table.shape.union} reads it through stg_{folder}__{table.type}.",
                6,
            ),
            "    columns:",
            f"      - name: {table.shape.key_column}",
            "        description: >",
            _folded(
                f"The row's key (decision 40): dbt_utils.generate_surrogate_key over {inputs}, the registry key "
                "first and then the fields measured unique for this layer.",
                10,
            ),
            "        data_tests: [not_null, unique]",
        ]
    return "\n".join(lines) + "\n"


# --- staging models -------------------------------------------------------------------------------------------


def _conformed(table: Table) -> list[str]:
    entry = table.entry
    if table.type == "places":
        if entry.get("name_field"):
            name = f"cast({column(entry['name_field'])} as varchar)"
        elif entry.get("name_constant"):
            name = f"cast({_sql_text(entry['name_constant'])} as varchar)"
        else:
            name = "cast(null as varchar)"
        category = (
            f"cast({column(entry['category_field'])} as varchar)" if entry.get("category_field") else "cast(null as varchar)"
        )
        return [f"{name} as name", f"{category} as category"]
    if table.type == "elevation":
        source = entry.get("elevation_source") or ""
        if source.startswith("field "):
            return [f"cast({column(source.removeprefix('field ').strip())} as varchar) as published_elevation"]
        if source == "geometry Z":
            return ["cast(null as varchar) as published_elevation"]
        raise ValueError(f"{table.key}: elevation_source {source!r} is neither 'field <name>' nor 'geometry Z'")
    raise ValueError(f"{table.key}: no staging shape for type {table.type}")


def stg_sql(folder: str, type_: str, type_tables: list[Table]) -> str:
    shape = SHAPES[type_]
    head = _comment(
        f"The {folder}/ folder's {type_.replace('_', ' ')} layers, conformed to {shape.union}'s columns: each "
        "layer's rename to the union's names and its key, nothing filtered (decision 40; a club's review gate is "
        "an intermediate's). The layer's own columns ride whole in `properties`, under dlt's names, so a rule "
        "downstream reads a field by the name its registry row gives it: json_merge_patch drops a member a "
        "patch sets to null, so `properties` is the base row without the geometry that travels beside it."
    )
    branches = []
    for table in type_tables:
        conformed = "".join(f"\n    {line}," for line in _conformed(table))
        branches.append(
            f"""select
    '{table.key}' as source_key,
    '{folder}' as club,
    {shape.key_column},{conformed}
    geom,
    json_merge_patch(
        to_json({table.base}),
        '{{"geom": null}}'
    ) as properties,
    _loaded_at
from {{{{ ref('{table.base}') }}}}"""
        )
    return SQL_MARK + head + "\n" + "\nunion all by name\n".join(branches) + "\n"


def models_yaml(folder: str, by_type: dict[str, list[Table]]) -> str:
    lines = [YAML_MARK + "version: 2", "", "models:"]
    for type_, type_tables in sorted(by_type.items()):
        shape = SHAPES[type_]
        keys = ", ".join(f"`{table.key}`" for table in type_tables)
        lines += [
            f"  - name: stg_{folder}__{type_}",
            "    description: >",
            _folded(
                f"The {folder}/ folder's {type_.replace('_', ' ')} layers ({keys}), one row per base row, renamed to "
                f"{shape.union}'s columns, with each layer's own columns in `properties`.",
                6,
            ),
            "    columns:",
            f"      - name: {shape.key_column}",
            "        description: The base model's key, carried.",
            "        data_tests: [not_null, unique]",
        ]
    return "\n".join(lines) + "\n"


# --- unions ---------------------------------------------------------------------------------------------------


def union_sql(type_: str, staging_models: list[str]) -> str:
    shape = SHAPES[type_]
    columns = ["source_key", "club", shape.key_column, *(name for name, _ in shape.columns), "geom", "properties", "_loaded_at"]
    head = _comment(
        f"Every {type_.replace('_', ' ')} row of the clubs' registered ArcGIS layers that pipeline/make_dbt_staging.py "
        "stages, one row each, unfiltered: a `union all by name` of every stg_<folder>__"
        f"{type_} it writes. The branch list is the registry's, written by the generator from sources.json and the "
        "extract's club folders, so a layer registered later joins by running it again. Nothing reads this yet: "
        "every layer here is held back by its sources.json row, and a mart that reads it must keep "
        "int_sources__publication's verdict."
    )
    select = ",\n    ".join(columns)
    branches = [f"select\n    {select}\nfrom {{{{ ref('{model}') }}}}" for model in staging_models]
    return SQL_MARK + "{{ config(materialized='table') }}\n" + head + "\n" + "\nunion all by name\n".join(branches) + "\n"


def union_yaml(type_: str, type_tables: list[Table]) -> str:
    shape = SHAPES[type_]
    lines = [
        YAML_MARK + "version: 2",
        "",
        "models:",
        f"  - name: {shape.union}",
        "    description: >",
        _folded(
            f"Every {type_.replace('_', ' ')} row of the {len(type_tables)} registered ArcGIS layers "
            f"pipeline/make_dbt_staging.py stages, unioned by name: {shape.row}. Each row carries its layer's "
            "registry key, the club folder that extracted it, the base model's key, the conformed columns below, "
            "its geometry as landed and its layer's own columns as `properties`. Unfiltered, and read by no mart.",
            6,
        ),
        "    data_tests:",
        "      # The lon/lat swap test, against the box each source's rows are held",
        "      # to (macros/generated_regions.sql, read by",
        "      # macros/lands_outside_its_region.sql).",
        "      - lands_in_the_region_its_source_publishes_in:",
        "          arguments:",
        "            geometry: geom",
        "    columns:",
        f"      - name: {shape.key_column}",
        "        description: The base model's key, carried; unique across the union because the registry key is its first input.",
        "        data_tests: [not_null, unique]",
        "      - name: source_key",
        "        description: The layer's sources.json key.",
        "        data_tests:",
        "          - not_null",
        "          - relationships:",
        "              arguments:",
        "                to: ref('stg_registry__sources')",
        "                field: source_key",
        "      - name: club",
        "        description: The extract folder that landed the row (trail_orgs.json's slug, `-` written `_`).",
        "        data_tests: [not_null]",
    ]
    for name, description in shape.columns:
        lines += [f"      - name: {name}", "        description: >", _folded(description, 10)]
    lines += [
        "      - name: geom",
        "        description: The feature's geometry as the layer published it, in OGC:CRS84, with a Z where the layer's vertices carry one.",
        "      - name: properties",
        "        description: The base row's own columns, under dlt's names, as JSON, the geometry left out.",
        "      - name: _loaded_at",
        "        description: When the extract landed the row (dlt's load stamp).",
    ]
    return "\n".join(lines) + "\n"


def hand_set_regions() -> set[str]:
    """The source keys macros/lands_outside_its_region.sql's own `regions` map lists: a box somebody set by hand."""
    import re

    text = (DBT / "macros" / "lands_outside_its_region.sql").read_text()
    block = re.search(r"\{%-?\s*set regions = \{(.*?)\}\s*-?%\}", text, re.S)
    return set(re.findall(r"'([a-z0-9_]+)':", block.group(1))) if block else set()


def regions_macro(all_tables: list[Table]) -> str:
    by_hand = hand_set_regions()
    keys = sorted(table.key for table in all_tables if table.key not in by_hand)
    cases = "\n".join(f"    when {{{{ column }}}} = '{key}' then '{DEFAULT_REGION}'" for key in keys)
    return (
        JINJA_MARK
        + """{#-
    The region box each source pipeline/make_dbt_staging.py stages is held
    to, as CASE branches on its key for macros/lands_outside_its_region.sql:
    us_and_territories for every one the macro's own `regions` map does not
    already list, the widest box that still catches a swapped United States
    point. @unvalidated as a fit, and never set from a server's extent (the
    generator's DEFAULT_REGION says why); each source's row of
    int_<type>__source_extents names the narrowest box its vertices fit.
    SQL rather than a returned dict, so SQLFluff's jinja templater renders
    it as dbt does.
-#}
{% macro generated_region_cases(column) -%}
"""
        + cases
        + """
{%- endmacro %}
"""
    )


# --- the run --------------------------------------------------------------------------------------------------


def render() -> dict[Path, str]:
    """Every file this writes, by path, from the registry and the extract's folders as they stand."""
    all_tables = tables()
    files: dict[Path, str] = {}
    by_folder: dict[str, list[Table]] = {}
    for table in all_tables:
        by_folder.setdefault(table.folder, []).append(table)
    staging_by_type: dict[str, list[str]] = {}
    tables_by_type: dict[str, list[Table]] = {}
    for folder, folder_tables in sorted(by_folder.items()):
        root = STAGING / folder
        files[root / f"_{folder}__generated__sources.yml"] = sources_yaml(folder, folder_tables)
        files[root / "base" / f"_{folder}__generated__base.yml"] = base_yaml(folder, folder_tables)
        by_type: dict[str, list[Table]] = {}
        for table in folder_tables:
            files[root / "base" / f"{table.base}.sql"] = base_sql(table)
            by_type.setdefault(table.type, []).append(table)
        for type_, type_tables in sorted(by_type.items()):
            files[root / f"stg_{folder}__{type_}.sql"] = stg_sql(folder, type_, type_tables)
            staging_by_type.setdefault(type_, []).append(f"stg_{folder}__{type_}")
            tables_by_type.setdefault(type_, []).extend(type_tables)
        files[root / f"_{folder}__generated__models.yml"] = models_yaml(folder, by_type)
    for type_, staging_models in sorted(staging_by_type.items()):
        shape = SHAPES[type_]
        files[INTERMEDIATE / type_ / f"{shape.union}.sql"] = union_sql(type_, staging_models)
        files[INTERMEDIATE / type_ / f"_{type_}__generated__intermediate.yml"] = union_yaml(type_, tables_by_type[type_])
    files[REGIONS_MACRO] = regions_macro(all_tables)
    return files


def generated_on_disk() -> set[Path]:
    """Every file under dbt/ that this generator wrote, by its first line."""
    found = set()
    for path in [*MODELS.rglob("*.sql"), *MODELS.rglob("*.yml"), REGIONS_MACRO]:
        if path.is_file() and GENERATED in path.read_text().split("\n", 1)[0]:
            found.add(path)
    return found


def differences(files: dict[Path, str]) -> list[str]:
    problems = []
    for path, text in sorted(files.items()):
        if not path.exists():
            problems.append(f"missing: {path.relative_to(PIPELINE)}")
        elif path.read_text() != text:
            problems.append(f"differs: {path.relative_to(PIPELINE)}")
        elif GENERATED not in path.read_text().split("\n", 1)[0]:
            problems.append(f"hand-written file in the way: {path.relative_to(PIPELINE)}")
    for path in sorted(generated_on_disk() - set(files)):
        problems.append(f"stale: {path.relative_to(PIPELINE)}")
    return problems


def write(files: dict[Path, str]) -> None:
    for path, text in files.items():
        if path.exists() and GENERATED not in path.read_text().split("\n", 1)[0]:
            raise FileExistsError(f"{path}: a hand-written file is where a generated one goes; nothing written")
    for path in generated_on_disk() - set(files):
        path.unlink()
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 naming each file that would change")
    args = parser.parse_args(argv)
    files = render()
    if args.check:
        problems = differences(files)
        for problem in problems:
            print(problem)
        return 1 if problems else 0
    write(files)
    print(f"{len(files)} generated files written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
