-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- NPS audio (the API's /multimedia/audio, national) (NPS, sources.json
-- `nps_multimedia_audio`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: `id`, NPS's own GUID for each item: present and unique on the 2 rows
-- of a sample read on 2026-10-04; the full read was refused by the public
-- DEMO_KEY's shared hourly limit (HTTP 429 OVER_RATE_LIMIT, 08:42 UTC). The
-- reader itself raises on a missing or repeated id within a read
-- (extract/_content.py's NpsContent), so a landed table is unique on it by
-- construction; that the whole list is, and that the id is stable from one
-- read to the next, is @unvalidated until the first monthly run under
-- NPS_API_KEY reads every row and re-measures it.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('nps', 'raw_nps__nps_multimedia_audio'),
        ['id', 'title', 'permalinkurl', 'versions']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_multimedia_audio'",
            'id',
        ]) }} as episode_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='episode_key', order_by='_dlt_id'
) }}
