-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- NPS Data API /places: every place the Park Service lists, nationally
-- (NPS, sources.json `nps_api_places`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: `id`, the API's own UUID for the item. @unvalidated as unique on the
-- live list: no real key has read the whole list (the demo key allows 10
-- requests an hour); the first monthly read with NPS_API_KEY settles it,
-- and duplicates_are_exact fails loudly if it is not.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('nps', 'raw_nps__nps_api_places'),
        ['id', 'geometry', 'title', 'tags']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_api_places'",
            'id',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
