-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- NPS Data API /places: every place the Park Service lists, nationally
-- (NPS, sources.json `nps_api_places`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: `id`, the API's own UUID for the item. Not unique on the first keyed
-- read: monthly run 17 (refresh-reference.yml 37232256991, 2026-10-04)
-- landed one `id` on two rows that differ, of 17,505 items the API counted,
-- and duplicates_are_exact failed the build. What differed was not kept,
-- and the demo key (10 requests an hour) cannot read the list again.
-- extract/_ogc.py's JsonFeatures now reads a paged list once more when it
-- holds fewer distinct keys than the API counts, and refuses copies that
-- still differ, naming the fields, so the next monthly read says whether
-- the list moved during the read (Reasoned) or the API lists one id twice.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('nps', 'raw_nps__nps_api_places'),
        ['id', 'geometry', 'title', 'tags']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_api_places'",
            'id',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
