-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Juan Bautista de Anza NHT recreation trails (NPS-hosted) (NPS,
-- sources.json `nps_anza_recreation_trails`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: GlobalID: unique and non-null on all 578 rows (measured 2026-10-03
-- over every row's attributes).
--
-- Dates: editdate, createdate, sourcedate, creationdate, editdate_1, the
-- layer's esriFieldTypeDate fields (sources.json `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (
            geometry,
            editdate,
            createdate,
            sourcedate,
            creationdate,
            editdate_1
        ),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(editdate / 1000) as editdate,
        to_timestamp(createdate / 1000) as createdate,
        to_timestamp(sourcedate / 1000) as sourcedate,
        to_timestamp(creationdate / 1000) as creationdate,
        to_timestamp(editdate_1 / 1000) as editdate_1
    from {{ raw_or_empty(
        source('nps', 'raw_nps__nps_anza_recreation_trails'),
        [
            'globalid',
            'geometry',
            'trname',
            'editdate:bigint',
            'createdate:bigint',
            'sourcedate:bigint',
            'creationdate:bigint',
            'editdate_1:bigint',
        ]
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_anza_recreation_trails'",
            'globalid',
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
