-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Overmountain Victory National Historic Trail historic route (NPS) (NPS,
-- sources.json `nps_overmountain_victory_nht`): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. A base
-- model, the one place this dataset is staged (decision 34).
--
-- Key: the geometry (every vertex at 6 decimal places): 43 of 43, and no
-- attribute column is unique (measured 2026-10-03 over every row).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('nps', 'raw_nps__nps_overmountain_victory_nht') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_overmountain_victory_nht'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
