-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- NPS tours (the API's /tours, national) (NPS, sources.json `nps_tours`):
-- every row, keyed and deduped (decision 40), with nothing filtered and
-- nothing joined. A base model, the one place this dataset is staged
-- (decision 34).
--
-- Key: `id`, NPS's own GUID for each item: present and unique on all 717
-- rows read 2026-10-04 (every page, two of 500), and the reader itself
-- raises on a missing or repeated id within a read (extract/_content.py's
-- NpsContent), so a landed table is unique on it by construction. The read
-- was the public DEMO_KEY's, which allows 10 requests an hour, so every row
-- was read; the first monthly run under NPS_API_KEY reads every row and re-
-- measures it.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('nps', 'raw_nps__nps_tours'),
        ['id', 'title']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_tours'",
            'id',
        ]) }} as hike_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='hike_key', order_by='_dlt_id'
) }}
