-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- NPS gallery assets, one per photo (the API's
-- /multimedia/galleries/assets, for the clubs' park codes) (NPS,
-- sources.json `nps_gallery_assets`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: `id`, NPS's own GUID for each item: present and unique on all 500
-- rows read 2026-10-04 (the first page of 500, asked for the 27 park codes
-- nps_alerts' map lists), and the reader itself raises on a missing or
-- repeated id within a read (extract/_content.py's NpsContent), so a landed
-- table is unique on it by construction. The read was the public
-- DEMO_KEY's, which allows 10 requests an hour, so the other rows were not
-- read; the first monthly run under NPS_API_KEY reads every row and re-
-- measures it.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('nps', 'raw_nps__nps_gallery_assets'),
        ['id', 'title', 'fileinfo', 'credit', 'constraintsinfo', 'permalinkurl']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_gallery_assets'",
            'id',
        ]) }} as photo_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='photo_key', order_by='_dlt_id'
) }}
