-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- NPS Data API /places: every place the Park Service lists, nationally
-- (NPS, sources.json `nps_api_places`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: `id` with `url`. `id` alone, the API's own UUID for the item, is not
-- unique: monthly run 17 (refresh-reference.yml 37232256991, 2026-10-04)
-- landed one `id` on two rows that differ, of 17,505 the API counted, and
-- duplicates_are_exact failed the build; run 18 (37245577210, 2026-10-05)
-- read the whole list twice and found the same: one `id`
-- (00415454-F93C-4D58-B612-BFC81442F17A) on two items differing in
-- `latLong`, `latitude`, `longitude`, `title` and `url`, so two different
-- places under one id rather than a list moving during the read. With `url`
-- the two are distinct (Reasoned from that refusal, which names the only
-- repeated id; not re-read here, since the demo key allows 10 requests an
-- hour and the list is 36 pages).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('nps', 'raw_nps__nps_api_places'),
        ['id', 'url', 'geometry', 'title', 'tags']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_api_places'",
            'id',
            'url',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
