-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Old Spanish National Historic Trail, feasibility study alignment (NPS)
-- (NPS, sources.json `nps_old_spanish_nht`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: One row, so the registry key alone is the key, as for
-- pcta_centerline (measured 2026-10-03: returnCountOnly 1).
--
-- Dates: datesent, the layer's esriFieldTypeDate fields (sources.json
-- `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, datesent),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(datesent / 1000) as datesent
    from {{ raw_or_empty(
        source('nps', 'raw_nps__nps_old_spanish_nht'),
        ['geometry', 'datesent:bigint']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_old_spanish_nht'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
