-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- NPS Boundary (Land Resources Division) (NPS, sources.json
-- `nps_park_boundaries`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: `GlobalID` is unique and non-null on all 442 rows read 2026-10-03.
--
-- Dates: date_edit, the layer's esriFieldTypeDate fields (sources.json
-- `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, date_edit),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(date_edit / 1000) as date_edit
    from {{ raw_or_empty(
        source('nps', 'raw_nps__nps_park_boundaries'),
        ['globalid', 'geometry', 'unit_name', 'date_edit:bigint']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_park_boundaries'",
            'globalid',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
