-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The nps/ folder's places layers, conformed to int_places__unioned's
-- columns: each layer's rename to the union's names and its key, nothing
-- filtered (decision 40; a club's review gate is an intermediate's). The
-- layer's own columns ride whole in `properties`, under dlt's names, so a
-- rule downstream reads a field by the name its registry row gives it:
-- json_merge_patch drops a member a patch sets to null, so `properties` is
-- the base row without the geometry that travels beside it.
select
    'grsm_municipal_boundaries' as source_key,
    'nps' as club,
    place_key,
    cast(name as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_nps__grsm_municipal_boundaries),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__grsm_municipal_boundaries') }}
union all by name
select
    'grsm_park_boundary_lines' as source_key,
    'nps' as club,
    place_key,
    cast(null as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_nps__grsm_park_boundary_lines),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__grsm_park_boundary_lines') }}
union all by name
select
    'nps_api_places' as source_key,
    'nps' as club,
    place_key,
    cast(title as varchar) as name,
    cast(tags as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_api_places),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_api_places') }}
union all by name
select
    'nps_legislated_wilderness' as source_key,
    'nps' as club,
    place_key,
    cast(name as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_legislated_wilderness),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_legislated_wilderness') }}
union all by name
select
    'nps_park_boundaries' as source_key,
    'nps' as club,
    place_key,
    cast(unit_name as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_park_boundaries),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_park_boundaries') }}
union all by name
select
    'pohe_trail_regions' as source_key,
    'nps' as club,
    place_key,
    cast(pohe_region as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_nps__pohe_trail_regions),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__pohe_trail_regions') }}
