-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The nps/ folder's trail lines layers, conformed to
-- int_trail_lines__unioned's columns: each layer's rename to the union's
-- names and its key, nothing filtered (decision 40; a club's review gate is
-- an intermediate's). The layer's own columns ride whole in `properties`,
-- under dlt's names, so a rule downstream reads a field by the name its
-- registry row gives it: json_merge_patch drops a member a patch sets to
-- null, so `properties` is the base row without the geometry that travels
-- beside it.
select
    'nps_ala_kahakai_alanui_aupuni' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(
        'Ala Kahakai National Historic Trail - Alanui Aupuni (SIHP '
        || '23300)' as varchar
    ) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_ala_kahakai_alanui_aupuni),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_ala_kahakai_alanui_aupuni') }}
union all by name
select
    'nps_ala_kahakai_kaawaloa' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(
        'Ala Kahakai National Historic Trail - Ka''awaloa Trail '
        || '(SIHP 14176)' as varchar
    ) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_ala_kahakai_kaawaloa),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_ala_kahakai_kaawaloa') }}
union all by name
select
    'nps_ala_kahakai_kiholo_puako' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(
        'Ala Kahakai National Historic Trail - Kiholo-Puako Trail '
        || '(SIHP 10308)' as varchar
    ) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_ala_kahakai_kiholo_puako),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_ala_kahakai_kiholo_puako') }}
union all by name
select
    'nps_ala_kahakai_kohala_hema' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(
        'Ala Kahakai National Historic Trail - Kohala Hema' as varchar
    ) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_ala_kahakai_kohala_hema),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_ala_kahakai_kohala_hema') }}
union all by name
select
    'nps_anza_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(trname as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_anza_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_anza_nht') }}
union all by name
select
    'nps_anza_recreation_trails' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(trname as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_anza_recreation_trails),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_anza_recreation_trails') }}
union all by name
select
    'nps_butterfield_overland_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(trname as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_butterfield_overland_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_butterfield_overland_nht') }}
union all by name
select
    'nps_butterfield_srs_route' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(
        'Butterfield Overland Trail Special Resource Study route' as varchar
    ) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_butterfield_srs_route),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_butterfield_srs_route') }}
union all by name
select
    'nps_california_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast('California National Historic Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_california_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_california_nht') }}
union all by name
select
    'nps_captain_john_smith_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(trail_name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_captain_john_smith_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_captain_john_smith_nht') }}
union all by name
select
    'nps_el_camino_tejas_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(
        'El Camino Real de los Tejas National Historic Trail' as varchar
    ) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_el_camino_tejas_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_el_camino_tejas_nht') }}
union all by name
select
    'nps_el_camino_tierra_adentro_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(trname as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_el_camino_tierra_adentro_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_el_camino_tierra_adentro_nht') }}
union all by name
select
    'nps_lewis_clark_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast('Lewis and Clark National Historic Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_lewis_clark_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_lewis_clark_nht') }}
union all by name
select
    'nps_lewis_clark_water_trails' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(trail_name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_lewis_clark_water_trails),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_lewis_clark_water_trails') }}
union all by name
select
    'nps_mormon_pioneer_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast('Mormon Pioneer National Historic Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_mormon_pioneer_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_mormon_pioneer_nht') }}
union all by name
select
    'nps_old_spanish_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast('Old Spanish National Historic Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_old_spanish_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_old_spanish_nht') }}
union all by name
select
    'nps_oregon_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast('Oregon National Historic Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_oregon_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_oregon_nht') }}
union all by name
select
    'nps_overmountain_victory_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(trailname as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_overmountain_victory_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_overmountain_victory_nht') }}
union all by name
select
    'nps_pony_express_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast('Pony Express National Historic Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_pony_express_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_pony_express_nht') }}
union all by name
select
    'nps_santa_fe_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(trname as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_santa_fe_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_santa_fe_nht') }}
union all by name
select
    'nps_star_spangled_banner_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(unit_name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_star_spangled_banner_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_star_spangled_banner_nht') }}
union all by name
select
    'nps_trail_of_tears_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(trname as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_trail_of_tears_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_trail_of_tears_nht') }}
union all by name
select
    'nps_washington_rochambeau_nht' as source_key,
    'nps' as club,
    trail_segment_key,
    cast(
        'Washington-Rochambeau Revolutionary Route National '
        || 'Historic Trail' as varchar
    ) as name,
    geom,
    json_merge_patch(
        to_json(base_nps__nps_washington_rochambeau_nht),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nps__nps_washington_rochambeau_nht') }}
