-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- FLTC hunting-season bypass routes (sources.json `fltc_hunting_bypasses`,
-- landed by extract/fltc/warnings.py's ArcgisLayer): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. Its
-- words, prose included, stay here: the staging model beside it carries
-- only facts (decision 55).
--
-- Key: fid, a server row id, so the geometry joins it (decision 40: never a
-- server row id alone). A reload that mints the ids again reads as every
-- notice removed and added, which moves a row's dates and never its
-- presence. @unvalidated as the smallest set of current values:
-- pipeline/spike_table_keys.py on the live layer settles it. Measured: Read
-- by this step at 2026-10-03T16:10:40Z: returnCountOnly under the row's
-- `where` answered 69, and `FID` is distinct on 69 of them
-- (returnDistinctValues), the key phase C builds on.
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ notice_raw_table(
        source('fltc', 'raw_fltc__fltc_hunting_bypasses'),
        ['geometry', 'fid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'fltc_hunting_bypasses'",
            'fid',
            geometry_key('geom'),
        ]) }} as notice_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
