-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- PA DCNR park advisories (ParkAdvisory API) (sources.json
-- `pa_dcnr_park_advisories`) in the shape every club notice shares
-- (int_closures__club_notices_unioned): renames and casts only. Each field
-- is read by its own name out of the row as JSON, so a field the source
-- drops or renames reads as null rather than failing every club's build.
-- The reader's shape: extract/_json_apis.py's DcnrParkAdvisories: an
-- advisory is {IsAlert, Message} and nothing else, so it has no title.
--
-- Only facts cross from base_: the source's id, title, category, status,
-- dates, link, a place name and its own geometry (decision 55, and
-- ORG_NOTICES.md section 7). Classifying a status, holding back an ended
-- notice and placing it are int_closures__club_notices' work.
with base as (
    select *
    from {{ ref('base_pasda__pa_dcnr_park_advisories') }}
),

attributes as (
    select *
    from base
),

fields as (
    select
        notice_key,
        _loaded_at,
        to_json(attributes) as row_json
    from attributes
)

select
    fields.notice_key,
    'pa_dcnr_park_advisories' as source_key,
    'pasda' as club,
    'warnings' as notice_type,
    'dcnr_park_advisories' as reader,
    'full' as listing,
    {{ notice_field('advisory_key') }} as source_id,
    cast(null as varchar) as title,
    cast(null as varchar) as category,
    {{ notice_field('isalert') }} as status,
    cast(null as timestamptz) as starts_at,
    cast(null as timestamptz) as ends_at,
    cast(null as timestamptz) as rescinded_at,
    cast(null as timestamptz) as source_edited_at,
    cast(null as varchar) as source_url,
    {{ notice_field('park_id') }} as locality,
    cast(null as varchar) as geom_geojson,
    fields._loaded_at
from fields
