-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- NC State Parks trail tables (ncparks.gov/state-parks/<park>/trails) (NC
-- State Parks, sources.json `nc_parks_trails`): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. A base
-- model, the one place this dataset is staged (decision 34).
--
-- Key: The park's trails page and the trail's name (`link`, `name`): unique
-- on all 407 rows read 2026-10-04. The name alone is not ('Lake Trail',
-- 'Laurel Trail', 'Summit Trail' and others name trails in two parks), and
-- the tables carry no id.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('nc_dpr', 'raw_nc_dpr__nc_parks_trails'),
        ['link', 'name']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nc_parks_trails'",
            'link',
            'name',
        ]) }} as hike_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='hike_key', order_by='_dlt_id'
) }}
