"""ATC's facility point layers, and the reviewed water distances for its shelters and campsites.

Bridges load though they do not ship: their registry row reads
`reaches_hikers: false` since #1674 — Stream crossings clutter the map: remove
the `crossing` waypoint type, its legend row, and the pipeline step that
derives it. Publication is decided downstream (ELT.md, "Load everything, gate
publication downstream").

reference/water_distance.json is generated by build_water_distance.py from
ATC's Campsite Sustainability Index layer and reviewed as a diff, so it loads
from this folder, the folder of whoever published the rows a person reviewed
(ELT.md, "Where a reviewed OurHike file loads"). The CSI layer itself has no
sources.json row yet, so it is not a resource here; build_water_distance.py
still fetches it.
"""

from extract._kinds import arcgis_layer, reviewed_file

LAYERS = ("shelters", "campsites", "parking", "viewpoints", "privies", "bridges")
WATER_DISTANCE = "reference/water_distance.json"

CLAIMS = (*LAYERS, WATER_DISTANCE)
RESOURCES = [*(arcgis_layer(key) for key in LAYERS), reviewed_file(WATER_DISTANCE, rows_key="sites")]
