-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The pasda/ folder's challenges sources, conformed to
-- int_challenges__club_unioned's columns: each source's rename to the
-- union's names and its key, nothing filtered (decision 40; a club's review
-- gate is an intermediate's). The source's own columns ride in
-- `properties`, under dlt's names, all but its prose: json_merge_patch
-- drops each member the patch sets to null, so a body, an episode's notes
-- or a page's wikitext stops at the base model (decision 55).
select
    'dcnr_geotrail' as source_key,
    'pasda' as club,
    challenge_item_key,
    cast(name as varchar) as name,
    cast(link as varchar) as link,
    json_merge_patch(
        to_json(base_pasda__dcnr_geotrail),
        '{}'
    ) as properties,
    _loaded_at
from {{ ref('base_pasda__dcnr_geotrail') }}
