-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Wisconsin DNR property hiking pages
-- (dnr.wisconsin.gov/topic/<kind>/<property>/recreation/hiking) (Wisconsin
-- DNR, sources.json `wi_dnr_hiking`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: The property's hiking page and the trail's name (`link`, `name`):
-- unique on all 170 rows read 2026-10-04. The name alone is not ('Blue
-- trail' is in two parks, 'Ice Age National Scenic Trail' in more).
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('wi_dnr', 'raw_wi_dnr__wi_dnr_hiking'),
        ['link', 'name']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'wi_dnr_hiking'",
            'link',
            'name',
        ]) }} as hike_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='hike_key', order_by='_dlt_id'
) }}
