-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Wasatch Mountain Club Hiking Trail Database (WMCHikesCopyToWeb.pdf) (WMC,
-- sources.json `wmc_hike_ratings`): every row, keyed and deduped (decision
-- 40), with nothing filtered and nothing joined. A base model, the one
-- place this dataset is staged (decision 34).
--
-- Key: The hike's name and its total ascent (`name`,
-- `elevation_gain_text`): unique on all 157 rows read 2026-10-04. The name
-- alone is not: 'SNAKE CREEK PASS FROM BRIGHTON LAKES TH.' is two rows,
-- 1,344 and 1,312 feet of ascent, and the table carries no id.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('wmc', 'raw_wmc__wmc_hike_ratings'),
        ['name', 'elevation_gain_text', 'link']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'wmc_hike_ratings'",
            'name',
            'elevation_gain_text',
        ]) }} as hike_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='hike_key', order_by='_dlt_id'
) }}
