-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- Ozark Trail Taum Sauk section conditions (sources.json
-- `ota_taum_sauk_conditions`, landed by extract/ota/closures.py's
-- PageNotice): every row, keyed and deduped (decision 40), with nothing
-- filtered and nothing joined. Its words, prose included, stay here: the
-- staging model beside it carries only facts (decision 55).
--
-- Key: url. Measured: no count is recorded on its sources.json row
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        *,
        {{ notice_row_version(
            source('ota', 'raw_ota__ota_taum_sauk_conditions')
        ) }} as row_version
    from {{ notice_raw_table(
        source('ota', 'raw_ota__ota_taum_sauk_conditions'),
        ['url']
    ) }}
),

keyed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ota_taum_sauk_conditions'",
            'url',
        ]) }} as notice_key,
        source.*
    from source
),

-- How many different rows share each key. More than one is what
-- duplicates_are_exact fails on, which only warns for a club notice
-- source: int_closures__gate holds the source instead, so one club's
-- conflicting rows hold that club's notices and nothing else.
renamed as (
    select
        keyed.*,
        count(distinct keyed.row_version)
            over (partition by keyed.notice_key)
            as key_versions
    from keyed
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
