-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- PHTA Trails (Potomac Heritage Trail Association's Google My Map) (Potomac
-- Heritage Trail Association, sources.json `phta_trails_map`): every row,
-- keyed and deduped (decision 40), with nothing filtered and nothing
-- joined. A base model, the one place this dataset is staged (decision 34).
--
-- Key: The geometry with `name`: unique on 180 of 183 after 3 exact copies,
-- which differ only in their position in the file (measured 2026-10-04 on
-- the live export; duplicates_are_exact sets the position aside). The
-- geometry alone is 173: a GPX import's 'Start of'/'End of' points share a
-- vertex with the next track's.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('pohe', 'raw_pohe__phta_trails_map') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'phta_trails_map'",
            geometry_key('geom'),
            'name',
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
