-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- Seward to Eagle River obstacles (sources.json
-- `alaska_trails_seward_obstacles`, landed by
-- extract/alaska_trails/warnings.py's ArcgisLayer): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. Its
-- words, prose included, stay here: the staging model beside it carries
-- only facts (decision 55).
--
-- Key: objectid, a server row id, so the geometry joins it (decision 40:
-- never a server row id alone). A reload that mints the ids again reads as
-- every notice removed and added, which moves a row's dates and never its
-- presence. @unvalidated as the smallest set of current values:
-- pipeline/spike_table_keys.py on the live layer settles it. Measured: Read
-- by this step at 2026-10-03T16:10:12Z: returnCountOnly under the row's
-- `where` answered 7, and `OBJECTID` is distinct on 7 of them
-- (returnDistinctValues), the key phase C builds on.
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ notice_raw_table(
        source(
            'alaska_trails',
            'raw_alaska_trails__alaska_trails_seward_obstacles'
        ),
        ['geometry', 'objectid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'alaska_trails_seward_obstacles'",
            'objectid',
            geometry_key('geom'),
        ]) }} as notice_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
