-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- North Country Trail spurs (NCTA) (NCTA, sources.json `ncta_spurs`): every
-- row, keyed and deduped (decision 40), with nothing filtered and nothing
-- joined. A base model, the one place this dataset is staged (decision 34).
--
-- Key: the geometry (every vertex at 6 decimal places): 304 of 304, and no
-- attribute column is unique (measured 2026-10-03 over every row).
--
-- Dates: updated, the layer's esriFieldTypeDate fields (sources.json
-- `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, updated),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(updated / 1000) as updated
    from {{ source('ncta', 'raw_ncta__ncta_spurs') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ncta_spurs'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
