-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- North Country Trail segments of the Finger Lakes Trail (NCTA, agol_flt)
-- (NCTA, sources.json `ncta_finger_lakes_trail`): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. A base
-- model, the one place this dataset is staged (decision 34).
--
-- Key: the geometry (every vertex at 6 decimal places): 417 of 417, and no
-- attribute column is unique (measured 2026-10-03 over every row).
--
-- Dates: built_on, updated, created_date, last_edited_date, the layer's
-- esriFieldTypeDate fields (sources.json `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, built_on, updated, created_date, last_edited_date),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(built_on / 1000) as built_on,
        to_timestamp(updated / 1000) as updated,
        to_timestamp(created_date / 1000) as created_date,
        to_timestamp(last_edited_date / 1000) as last_edited_date
    from {{ raw_or_empty(
        source('ncta', 'raw_ncta__ncta_finger_lakes_trail'),
        [
            'geometry',
            'seg_name',
            'built_on:bigint',
            'updated:bigint',
            'created_date:bigint',
            'last_edited_date:bigint',
        ]
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ncta_finger_lakes_trail'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
