-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Superior Hiking Trail, NCTA's public layer (agol_sht_public) (NCTA,
-- sources.json `ncta_superior_hiking_trail`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: the geometry (every vertex at 6 decimal places): 272 of 272, and no
-- attribute column is unique (measured 2026-10-03 over every row).
--
-- Dates: built_on, updated, the layer's esriFieldTypeDate fields
-- (sources.json `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, built_on, updated),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(built_on / 1000) as built_on,
        to_timestamp(updated / 1000) as updated
    from {{ source('ncta', 'raw_ncta__ncta_superior_hiking_trail') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ncta_superior_hiking_trail'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
