-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- NBATC Blue Blazer Program form
-- (home.nbatc.org/pdfs/BlueBlazeTrailHike.pdf) (NBATC, sources.json
-- `nbatc_blue_blazer`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: `number`, the trail's place in the table: unique on all 20 rows read
-- 2026-10-04, as are the names.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('nbatc', 'raw_nbatc__nbatc_blue_blazer'),
        ['number', 'name', 'link']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nbatc_blue_blazer'",
            'number',
        ]) }} as challenge_item_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='challenge_item_key', order_by='_dlt_id'
) }}
