-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- A.T. centerline with elevation (ATC's ATX Ratings, Centerline Current)
-- (ATC, sources.json `atc_atx_centerline`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: `GlobalID`: unique on all 697 rows (the elevation read's own
-- measurement, 2026-10-03, in `notes`), the layer's own id. `id_field`
-- names the object id, which a reload mints again (decision 40). `full_ID`
-- is unique only on the 679 rows with a geometry: OBJECTID 681 to 698
-- repeat segment 25-01-03 with none, so each keeps its own GlobalID and its
-- row.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('atc', 'raw_atc__atc_atx_centerline') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'atc_atx_centerline'",
            'globalid',
        ]) }} as elevation_feature_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='elevation_feature_key', order_by='_dlt_id'
) }}
