-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- DEC Lands (state land units) (NYS DEC, sources.json `dec_lands`): every
-- row, keyed and deduped (decision 40), with nothing filtered and nothing
-- joined. A base model, the one place this dataset is staged (decision 34).
--
-- Key: the geometry (every vertex as the layer serves it): 3,234 of 3,234,
-- no exact copies; the attribute pair (LANDS_UID, ACRES) is unique too,
-- LANDS_UID alone repeating on 3 rows (measured 2026-10-03 by reading every
-- row and every vertex as the extract reads the layer (f=geojson, outSR
-- 4326), under lib/user_agent.py's USER_AGENT, robots.txt first). The
-- geometry stands alone because it is the smallest key: phase C's base
-- model keys and dedupes on it.
--
-- Dates: updated, the layer's esriFieldTypeDate fields (sources.json
-- `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, updated),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(updated / 1000) as updated
    from {{ raw_or_empty(
        source('nysdec', 'raw_nysdec__dec_lands'),
        ['geometry', 'facility', 'category', 'updated:bigint']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'dec_lands'",
            geometry_key('geom'),
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
