"""The API this build serves must not break the last release's clients (#374).

RELEASING.md §8c, surface 2. Two halves, and both are load-bearing:

*The real check.* `openapi_baseline.json` against `app.openapi()`. This is the
one that fails during ordinary work, when somebody removes a response field
without noticing an old phone reads it.

*The synthetic cases.* One per rule, on hand-built documents. Without them the
real check is untestable: it passes today because the API is compatible with
itself, and it would pass exactly as loudly if `compare` returned `[]`
unconditionally. Each case below is a break the differ must find, and
`test_an_unchanged_document_is_clean` is the one it must not invent.

The asymmetry between request and response is the thing most likely to look
like a bug on first reading - see the module docstring in
scripts/check_openapi_compat.py. An old client WRITES requests and READS
responses, so the direction a change is safe in flips between them.
"""

import copy
import json

import pytest

from scripts.check_openapi_compat import (
    BASELINE_PATH,
    compare,
    current_document,
    load_baseline,
)


def _document(schema: dict, *, role: str = "response") -> dict:
    """A minimal but structurally real OpenAPI document with one schema.

    `role` decides whether the schema hangs off a requestBody or a response,
    which is what selects the rule set being exercised.
    """
    reference = {"$ref": "#/components/schemas/Thing"}
    operation: dict = {"responses": {"200": {"content": {"application/json": {"schema": reference}}}}}
    if role == "request":
        operation = {
            "requestBody": {"content": {"application/json": {"schema": reference}}},
            "responses": {"204": {"description": "no content"}},
        }
    return {
        "openapi": "3.1.0",
        "paths": {"/things": {"post" if role == "request" else "get": operation}},
        "components": {"schemas": {"Thing": schema}},
    }


THING = {
    "type": "object",
    "properties": {"id": {"type": "string"}, "note": {"type": "string"}},
    "required": ["id"],
}


# --- The real check -------------------------------------------------------


def test_this_build_is_compatible_with_the_baseline():
    assert compare(load_baseline(), current_document()) == []


def test_the_baseline_is_present_and_substantial():
    """Guards the failure mode that would make every other test here a lie:
    an empty or missing baseline compares clean against anything.

    Same principle as tests/test_preferences_contract.py - "the one thing
    this must never do is pass because it failed to find the file."
    """
    baseline = load_baseline()

    assert len(baseline["paths"]) >= 15
    assert len(baseline["components"]["schemas"]) >= 30


def test_a_missing_baseline_raises_rather_than_passing(tmp_path):
    with pytest.raises(FileNotFoundError):
        load_baseline(tmp_path / "nothing-here.json")


def test_the_baseline_on_disk_is_what_the_writer_produces():
    """It is regenerated by `--write`, so it must be byte-comparable to that
    output modulo the app's current shape - otherwise a hand-edit could sit
    in the file undetected."""
    stored = json.loads(BASELINE_PATH.read_text())

    assert stored == json.loads(json.dumps(stored, sort_keys=True))


# --- One synthetic case per rule ------------------------------------------


def test_an_unchanged_document_is_clean():
    """The differ must not invent breaks. Without this, a `compare` that
    returned a break for everything would pass every other test here."""
    assert compare(_document(THING), _document(THING)) == []


def test_a_removed_path_is_a_break():
    current = _document(THING)
    current["paths"] = {}

    breaks = compare(_document(THING), current)

    assert [item.rule for item in breaks] == ["path removed"]


def test_a_removed_operation_is_a_break():
    current = _document(THING)
    current["paths"]["/things"] = {"put": {"responses": {}}}

    breaks = compare(_document(THING), current)

    assert "operation removed" in [item.rule for item in breaks]


def test_a_removed_response_field_is_a_break():
    shrunk = copy.deepcopy(THING)
    del shrunk["properties"]["note"]

    breaks = compare(_document(THING), _document(shrunk))

    assert [item.rule for item in breaks] == ["response field removed"]
    assert breaks[0].where == "Thing.note"


def test_a_response_field_demoted_to_optional_is_a_break():
    """The same removal, spread over two releases. An old client that reads
    `id` unconditionally does not care that the server still sometimes sends
    it."""
    loosened = copy.deepcopy(THING)
    loosened["required"] = []

    breaks = compare(_document(THING), _document(loosened))

    assert [item.rule for item in breaks] == ["response field no longer guaranteed"]


def test_an_added_response_field_is_not_a_break():
    """An old client ignores what it does not know."""
    grown = copy.deepcopy(THING)
    grown["properties"]["added_later"] = {"type": "string"}

    assert compare(_document(THING), _document(grown)) == []


def test_a_newly_required_request_field_is_a_break():
    stricter = copy.deepcopy(THING)
    stricter["required"] = ["id", "note"]

    breaks = compare(_document(THING, role="request"), _document(stricter, role="request"))

    assert [item.rule for item in breaks] == ["request field newly required"]
    assert breaks[0].where == "Thing.note"


def test_a_newly_required_response_field_is_not_a_break():
    """The direction that flips. A server promising MORE about what it sends
    cannot break a reader."""
    stricter = copy.deepcopy(THING)
    stricter["required"] = ["id", "note"]

    assert compare(_document(THING), _document(stricter)) == []


def test_a_removed_request_enum_member_is_a_break():
    old = copy.deepcopy(THING)
    old["properties"]["kind"] = {"enum": ["blowdown", "trash", "thanks"]}
    new = copy.deepcopy(old)
    new["properties"]["kind"] = {"enum": ["blowdown", "trash"]}

    breaks = compare(_document(old, role="request"), _document(new, role="request"))

    assert [item.rule for item in breaks] == ["request enum member removed"]
    assert "thanks" in breaks[0].detail


def test_a_removed_response_enum_member_is_not_a_break():
    """Every enum this API returns is rendered through a client-side lookup
    with a fallback, so an unknown or absent member degrades to a neutral
    label rather than throwing."""
    old = copy.deepcopy(THING)
    old["properties"]["kind"] = {"enum": ["verified", "resolved", "dismissed"]}
    new = copy.deepcopy(old)
    new["properties"]["kind"] = {"enum": ["verified", "resolved"]}

    assert compare(_document(old), _document(new)) == []


def test_a_schema_reached_only_through_nesting_is_still_checked():
    """Roles resolve transitively. Stopping at the top level would exempt
    exactly the nested shapes most likely to change - `ReportOut` inside a
    moderation queue, for instance."""
    baseline = _document(THING)
    baseline["components"]["schemas"]["Thing"] = {
        "type": "object",
        "properties": {"inner": {"$ref": "#/components/schemas/Inner"}},
    }
    baseline["components"]["schemas"]["Inner"] = {
        "type": "object",
        "properties": {"kept": {"type": "string"}, "dropped": {"type": "string"}},
    }
    current = copy.deepcopy(baseline)
    del current["components"]["schemas"]["Inner"]["properties"]["dropped"]

    breaks = compare(baseline, current)

    assert [item.where for item in breaks] == ["Inner.dropped"]


def test_a_removed_schema_that_an_operation_used_is_a_break():
    current = _document(THING)
    current["components"]["schemas"] = {}

    breaks = compare(_document(THING), current)

    assert "schema removed" in [item.rule for item in breaks]


def test_an_orphaned_schema_is_not_part_of_the_contract():
    """A component no operation references is not on the wire, so removing
    it cannot break a client."""
    baseline = _document(THING)
    baseline["components"]["schemas"]["NeverReferenced"] = {"type": "object"}
    current = _document(THING)

    assert compare(baseline, current) == []
