-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The ncta/ folder's trail lines layers, conformed to
-- int_trail_lines__unioned's columns: each layer's rename to the union's
-- names and its key, nothing filtered (decision 40; a club's review gate is
-- an intermediate's). The layer's own columns ride whole in `properties`,
-- under dlt's names, so a rule downstream reads a field by the name its
-- registry row gives it: json_merge_patch drops a member a patch sets to
-- null, so `properties` is the base row without the geometry that travels
-- beside it.
select
    'ncta_finger_lakes_trail' as source_key,
    'ncta' as club,
    trail_segment_key,
    cast(seg_name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_ncta__ncta_finger_lakes_trail),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_ncta__ncta_finger_lakes_trail') }}
union all by name
select
    'ncta_nearby_trails' as source_key,
    'ncta' as club,
    trail_segment_key,
    cast(seg_name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_ncta__ncta_nearby_trails),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_ncta__ncta_nearby_trails') }}
union all by name
select
    'ncta_spurs' as source_key,
    'ncta' as club,
    trail_segment_key,
    cast(seg_name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_ncta__ncta_spurs),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_ncta__ncta_spurs') }}
union all by name
select
    'ncta_superior_hiking_trail' as source_key,
    'ncta' as club,
    trail_segment_key,
    cast(seg_name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_ncta__ncta_superior_hiking_trail),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_ncta__ncta_superior_hiking_trail') }}
