-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The ncta/ folder's elevation layers, conformed to
-- int_elevation__unioned's columns: each layer's rename to the union's
-- names and its key, nothing filtered (decision 40; a club's review gate is
-- an intermediate's). The layer's own columns ride whole in `properties`,
-- under dlt's names, so a rule downstream reads a field by the name its
-- registry row gives it: json_merge_patch drops a member a patch sets to
-- null, so `properties` is the base row without the geometry that travels
-- beside it.
select
    'ncta_kek_mileage_elev' as source_key,
    'ncta' as club,
    elevation_feature_key,
    cast(z as varchar) as published_elevation,
    geom,
    json_merge_patch(
        to_json(base_ncta__ncta_kek_mileage_elev),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_ncta__ncta_kek_mileage_elev') }}
