-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Forest Park Trailheads (Forest Park Conservancy's Google My Map) (Forest
-- Park Conservancy, sources.json `fpc_forest_park_trailheads`): every row,
-- keyed and deduped (decision 40), with nothing filtered and nothing
-- joined. A base model, the one place this dataset is staged (decision 34).
--
-- Key: The geometry alone: unique on 19 of 19 (measured 2026-10-04 on the
-- live export). `name` is also unique.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('fpc', 'raw_fpc__fpc_forest_park_trailheads'),
        ['geometry', 'name', 'folder']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'fpc_forest_park_trailheads'",
            geometry_key('geom'),
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
