-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Trails, Portland region (Oregon Metro RLIS) (Oregon Metro, sources.json
-- `oregon_metro_trails`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: geometry with LENGTH: 28,834 of 28,834 (measured 2026-10-03 over
-- every row and vertex). Geometry alone is 28,831: three shapes carry two
-- rows each that differ only in LENGTH, which is null on 268 rows. TRAILID
-- is unique on 28,831. The weakest key in this wave after Baywide's, and
-- the place a re-measure should start.
--
-- Dates: last_edit, the layer's esriFieldTypeDate fields (sources.json
-- `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, last_edit),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(last_edit / 1000) as last_edit
    from {{ raw_or_empty(
        source('fpc', 'raw_fpc__oregon_metro_trails'),
        ['length', 'geometry', 'trailname', 'last_edit:bigint']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'oregon_metro_trails'",
            geometry_key('geom'),
            'length',
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
