-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The wa_rco/ folder's places layers, conformed to int_places__unioned's
-- columns: each layer's rename to the union's names and its key, nothing
-- filtered (decision 40; a club's review gate is an intermediate's). The
-- layer's own columns ride whole in `properties`, under dlt's names, so a
-- rule downstream reads a field by the name its registry row gives it:
-- json_merge_patch drops a member a patch sets to null, so `properties` is
-- the base row without the geometry that travels beside it.
select
    'wa_public_lands_inventory' as source_key,
    'wa_rco' as club,
    place_key,
    cast(agency_management_unit as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_wa_rco__wa_public_lands_inventory),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_wa_rco__wa_public_lands_inventory') }}
union all by name
select
    'wa_recreation_areas' as source_key,
    'wa_rco' as club,
    place_key,
    cast(name as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_wa_rco__wa_recreation_areas),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_wa_rco__wa_recreation_areas') }}
