-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Randolph Mountain Club Recommended Hikes (Recommended-Hikes-1.pdf) (RMC,
-- sources.json `rmc_recommended_hikes`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: The walk's group heading and its name (`section`, `name`): unique on
-- all 47 rows read 2026-10-04, and the names alone are unique too; the pair
-- is kept because a peak route is named by its trails, and the same trails
-- climb more than one peak (Lowe's Path is Adams's route and the first leg
-- of one of Jefferson's).
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('rmc', 'raw_rmc__rmc_recommended_hikes'),
        ['section', 'name', 'link']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'rmc_recommended_hikes'",
            'section',
            'name',
        ]) }} as hike_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='hike_key', order_by='_dlt_id'
) }}
