-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- NPS Road Events (WZDx) (sources.json `nps_road_events`, landed by
-- extract/nps/warnings.py's NpsRoadEvents): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. Its words, prose
-- included, stay here: the staging model beside it carries only facts
-- (decision 55).
--
-- Key: id. Measured: `Id` (a GUID, unique on 86 of 86 in that one read;
-- stable across reads is @unvalidated) and `_id` (0 to 85, the position in
-- the answer, so never a key) (sources.json's notes, in part)
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ notice_raw_table(
        source('nps', 'raw_nps__nps_road_events'),
        ['geometry', 'id']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_road_events'",
            'id',
        ]) }} as notice_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
