-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- Great Smoky Mountains NP trails: access not open (sources.json
-- `grsm_trails_access`, landed by extract/nps/closures.py's ArcgisLayer):
-- every row, keyed and deduped (decision 40), with nothing filtered and
-- nothing joined. Its words, prose included, stay here: the staging model
-- beside it carries only facts (decision 55).
--
-- Key: globalid. Measured: Read by this step at 2026-10-03T16:08:15Z:
-- returnCountOnly under the row's `where` answered 26, and `GlobalID` is
-- distinct on 26 of them (returnDistinctValues), the key phase C builds on.
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        {{ notice_row_version(
            source('nps', 'raw_nps__grsm_trails_access')
        ) }} as row_version
    from {{ notice_raw_table(
        source('nps', 'raw_nps__grsm_trails_access'),
        ['geometry', 'globalid']
    ) }}
),

keyed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'grsm_trails_access'",
            'globalid',
        ]) }} as notice_key,
        source.*
    from source
),

-- How many different rows share each key. More than one is what
-- duplicates_are_exact fails on, which only warns for a club notice
-- source: int_closures__gate holds the source instead, so one club's
-- conflicting rows hold that club's notices and nothing else.
renamed as (
    select
        keyed.*,
        count(distinct keyed.row_version)
            over (partition by keyed.notice_key)
            as key_versions
    from keyed
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
