-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- NPS Road Events (WZDx) (sources.json `nps_road_events`, landed by
-- extract/nps/warnings.py's NpsRoadEvents): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. Its words, prose
-- included, stay here: the staging model beside it carries only facts
-- (decision 55).
--
-- Key: id. Measured: `Id` (a GUID, unique on 86 of 86 in that one read;
-- stable across reads is @unvalidated) and `_id` (0 to 85, the position in
-- the answer, so never a key) (sources.json's notes, in part)
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        {{ notice_row_version(
            source('nps', 'raw_nps__nps_road_events')
        ) }} as row_version
    from {{ notice_raw_table(
        source('nps', 'raw_nps__nps_road_events'),
        ['geometry', 'id']
    ) }}
),

keyed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_road_events'",
            'id',
        ]) }} as notice_key,
        source.*
    from source
),

-- How many different rows share each key. More than one is what
-- duplicates_are_exact fails on, which only warns for a club notice
-- source: int_closures__gate holds the source instead, so one club's
-- conflicting rows hold that club's notices and nothing else.
renamed as (
    select
        keyed.*,
        count(distinct keyed.row_version)
            over (partition by keyed.notice_key)
            as key_versions
    from keyed
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
