-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- NPS Alerts, for the park codes the clubs draw on (sources.json
-- `nps_alerts`, landed by extract/nps/warnings.py's NpsAlerts): every row,
-- keyed and deduped (decision 40), with nothing filtered and nothing
-- joined. Its words, prose included, stay here: the staging model beside it
-- carries only facts (decision 55).
--
-- Key: id. Measured: Fields per alert (measured on the national list's
-- first 50, 2026-10-03): id (a GUID, unique on 50 of 50), url (empty on 31
-- of 50), title, parkCode, description, category (Park Closure 25, Caution
-- 11, Information 8, Danger 6), relatedRoadEvents (a list of {title, id,
-- type, url}), lastIndexedDate ('2026-10-02 00:00:00.0', an index date, not
-- a start or an end).
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select *
    from {{ notice_raw_table(
        source('nps', 'raw_nps__nps_alerts'),
        ['id']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nps_alerts'",
            'id',
        ]) }} as notice_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
