-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The cumberland/ folder's points of interest layers, conformed to
-- int_points_of_interest__club_unioned's columns: each layer's rename to
-- the union's names and its key, nothing filtered (decision 40; a club's
-- review gate is an intermediate's). The layer's own columns ride whole in
-- `properties`, under dlt's names, so a rule downstream reads a field by
-- the name its registry row gives it: json_merge_patch drops a member a
-- patch sets to null, so `properties` is the base row without the geometry
-- that travels beside it.
select
    'cumberland_trail_campsites' as source_key,
    'cumberland' as club,
    poi_key,
    cast(name as varchar) as name,
    cast(null as varchar) as category,
    cast(poi_key as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_cumberland__cumberland_trail_campsites),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_cumberland__cumberland_trail_campsites') }}
union all by name
select
    'cumberland_trail_natural_features' as source_key,
    'cumberland' as club,
    poi_key,
    cast(name as varchar) as name,
    cast(null as varchar) as category,
    cast(poi_key as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_cumberland__cumberland_trail_natural_features),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_cumberland__cumberland_trail_natural_features') }}
union all by name
select
    'cumberland_trail_trailheads' as source_key,
    'cumberland' as club,
    poi_key,
    cast(name as varchar) as name,
    cast(status as varchar) as category,
    cast(poi_key as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_cumberland__cumberland_trail_trailheads),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_cumberland__cumberland_trail_trailheads') }}
union all by name
select
    'tn_state_parks_campgrounds' as source_key,
    'cumberland' as club,
    poi_key,
    cast(campgrnd_name as varchar) as name,
    cast(campgrnd_type as varchar) as category,
    cast(globalid as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_cumberland__tn_state_parks_campgrounds),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_cumberland__tn_state_parks_campgrounds') }}
union all by name
select
    'tn_state_parks_campsites' as source_key,
    'cumberland' as club,
    poi_key,
    cast(site_name as varchar) as name,
    cast(campgrnd_type as varchar) as category,
    cast(globalid as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_cumberland__tn_state_parks_campsites),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_cumberland__tn_state_parks_campsites') }}
union all by name
select
    'tn_state_parks_hiking_assets' as source_key,
    'cumberland' as club,
    poi_key,
    cast(name as varchar) as name,
    cast(asset_type as varchar) as category,
    cast(globalid as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_cumberland__tn_state_parks_hiking_assets),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_cumberland__tn_state_parks_hiking_assets') }}
