-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The iata/ folder's points of interest layers, conformed to
-- int_points_of_interest__club_unioned's columns: each layer's rename to
-- the union's names and its key, nothing filtered (decision 40; a club's
-- review gate is an intermediate's). The layer's own columns ride whole in
-- `properties`, under dlt's names, so a rule downstream reads a field by
-- the name its registry row gives it: json_merge_patch drops a member a
-- patch sets to null, so `properties` is the base row without the geometry
-- that travels beside it.
select
    'iata_camping' as source_key,
    'iata' as club,
    poi_key,
    cast(description as varchar) as name,
    cast(camp_type as varchar) as category,
    cast(poi_key as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_iata__iata_camping),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_iata__iata_camping') }}
union all by name
select
    'iata_parking' as source_key,
    'iata' as club,
    poi_key,
    cast(description as varchar) as name,
    cast(parking_type as varchar) as category,
    cast(poi_key as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_iata__iata_parking),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_iata__iata_parking') }}
union all by name
select
    'iata_water' as source_key,
    'iata' as club,
    poi_key,
    cast(description as varchar) as name,
    cast(feature_type as varchar) as category,
    cast(poi_key as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_iata__iata_water),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_iata__iata_water') }}
