-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Naches Pass Trail, 2020 mapping (OCTA) (OCTA, sources.json
-- `octa_naches_pass_trail`): every row, keyed and deduped (decision 40),
-- with nothing filtered and nothing joined. A base model, the one place
-- this dataset is staged (decision 34).
--
-- Key: Name: unique and non-null on all 83 rows (measured 2026-10-03 over
-- every row's attributes).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('octa', 'raw_octa__octa_naches_pass_trail'),
        ['name', 'geometry']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'octa_naches_pass_trail'",
            'name',
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
