-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Klamath/Fremont Trail, atlas page 71 (OCTA) (OCTA, sources.json
-- `octa_klamath_fremont_trail_71`): every row, keyed and deduped (decision
-- 40), with nothing filtered and nothing joined. A base model, the one
-- place this dataset is staged (decision 34).
--
-- Key: One row, so the registry key alone is the key, as for
-- pcta_centerline (measured 2026-10-03: returnCountOnly 1).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('octa', 'raw_octa__octa_klamath_fremont_trail_71'),
        ['geometry']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'octa_klamath_fremont_trail_71'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
