-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- USGS Volcano Hazards: volcanoes at an elevated alert level (sources.json
-- `usgs_elevated_volcanoes`) in the shape every club notice shares
-- (int_closures__club_notices_unioned): renames and casts only. Each field
-- is read by its own name out of the row as JSON, so a field the source
-- drops or renames reads as null rather than failing every club's build.
-- The reader's shape: extract/_json_apis.py's USGS_VOLCANO_TEXT;
-- `notice_data` is USGS's wording and stays in base.
--
-- Only facts cross from base_: the source's id, title, category, status,
-- dates, link, a place name and its own geometry (decision 55, and
-- ORG_NOTICES.md section 7). Classifying a status, holding back an ended
-- notice and placing it are int_closures__club_notices' work.
with base as (
    select *
    from {{ ref('base_usgs__usgs_elevated_volcanoes') }}
),

attributes as (
    select *
    from base
),

fields as (
    select
        notice_key,
        _loaded_at,
        to_json(attributes) as row_json
    from attributes
)

select
    fields.notice_key,
    'usgs_elevated_volcanoes' as source_key,
    'usgs' as club,
    'warnings' as notice_type,
    'usgs_elevated_volcanoes' as reader,
    'full' as listing,
    {{ notice_field('vnum') }} as source_id,
    {{ notice_field('volcano_name') }} as title,
    {{ notice_field('alert_level') }} as category,
    {{ notice_field('color_code') }} as status,
    cast(null as timestamptz) as starts_at,
    cast(null as timestamptz) as ends_at,
    cast(null as timestamptz) as rescinded_at,
    {{ notice_instant(notice_field('sent_utc')) }} as source_edited_at,
    {{ notice_field('notice_url') }} as source_url,
    {{ notice_field('obs_abbr') }} as locality,
    cast(null as varchar) as geom_geojson,
    fields._loaded_at
from fields
