-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Utah State Parks campsites (UGRC's Campsites Aspira) (Utah UGRC,
-- sources.json `utah_state_park_campsites`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: the registry's `id_field`; its row records no measurement of it.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('utah_sgid', 'raw_utah_sgid__utah_state_park_campsites'),
        ['site_id', 'geometry', 'site_name']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'utah_state_park_campsites'",
            'site_id',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
