-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Utah trailheads (UGRC) (Utah UGRC, sources.json `utah_trailheads`): every
-- row, keyed and deduped (decision 40), with nothing filtered and nothing
-- joined. A base model, the one place this dataset is staged (decision 34).
--
-- Key: (PrimaryName, TrailheadID): 568 of 568 (measured 2026-10-04 by
-- reading every row and every vertex as the extract reads the layer
-- (f=geojson, outSR 4326), under lib/user_agent.py's USER_AGENT, robots.txt
-- first); TrailheadID is null on 9 rows. The geometry alone is 567: one
-- point carries two trailheads that differ only in TrailheadID.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('utah_sgid', 'raw_utah_sgid__utah_trailheads') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'utah_trailheads'",
            'primaryname',
            'trailheadid',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
