-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- WA RCO trailheads: status (sources.json `wa_rco_trailhead_status`, landed
-- by extract/wa_rco/closures.py's ArcgisLayer): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. Its
-- words, prose included, stay here: the staging model beside it carries
-- only facts (decision 55).
--
-- Key: globalid. Measured: Read by this step at 2026-10-03T16:12:23Z:
-- returnCountOnly under the row's `where` answered 202, and `GlobalID` is
-- distinct on 202 of them (returnDistinctValues), the key phase C builds
-- on.
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ notice_raw_table(
        source('wa_rco', 'raw_wa_rco__wa_rco_trailhead_status'),
        ['geometry', 'globalid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'wa_rco_trailhead_status'",
            'globalid',
        ]) }} as notice_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
