-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Land Ownership within 10 miles of the Arizona Trail (AZGeo, sources.json
-- `azt_land_ownership`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: `OWNER` is unique and non-null on all 32 rows read 2026-10-03.
--
-- Dates: edit_date, the layer's esriFieldTypeDate fields (sources.json
-- `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, edit_date),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(edit_date / 1000) as edit_date
    from {{ source('azgeo', 'raw_azgeo__azt_land_ownership') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'azt_land_ownership'",
            'owner',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
