-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- CDT trailheads, access points and mail drops (CDTC's own CDTC_Waypoints
-- layer) (CDTC, sources.json `cdtc_trailheads_and_mail`): every row, keyed
-- and deduped (decision 40), with nothing filtered and nothing joined. A
-- base model, the one place this dataset is staged (decision 34).
--
-- Key: the geometry with WP_Type: 292 of 292 (measured 2026-10-04 by
-- reading every row and every vertex as the extract reads the layer
-- (f=geojson, outSR 4326), under lib/user_agent.py's USER_AGENT, robots.txt
-- first); WP_Type is null on 81 rows, so the key leans on nulls. The
-- geometry alone leaves one point carrying two waypoints of two types.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('cdtc', 'raw_cdtc__cdtc_trailheads_and_mail'),
        ['wp_type', 'geometry', 'name', 'objectid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'cdtc_trailheads_and_mail'",
            geometry_key('geom'),
            'wp_type',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
