-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Mountains to Sound Greenway National Heritage Area boundary (MTSG,
-- sources.json `mtsg_heritage_area_boundary`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: `Zone` is unique and non-null on all 1 rows read 2026-10-03.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('mtsg', 'raw_mtsg__mtsg_heritage_area_boundary'),
        ['zone', 'geometry']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'mtsg_heritage_area_boundary'",
            'zone',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
