-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Mountains to Sound Greenway map locations: trailheads, campgrounds, parks
-- and heritage sites (WordPress REST) (MTSG, sources.json
-- `mtsg_map_locations`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: `id`, the WordPress post id: unique on 185 of 185 (measured
-- 2026-10-04 on both pages). A post id is the site's own primary key, kept
-- across edits, not a row number a reload mints.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('mtsg', 'raw_mtsg__mtsg_map_locations'),
        ['id', 'geometry', 'title', 'icon']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'mtsg_map_locations'",
            'id',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
