-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Catamount Trail backcountry ski zones (web map CSV) (Catamount Trail
-- Association, sources.json `catamount_backcountry_zones`): every row,
-- keyed and deduped (decision 40), with nothing filtered and nothing
-- joined. A base model, the one place this dataset is staged (decision 34).
--
-- Key: The geometry alone: unique on 6 of 6 (measured 2026-10-04).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('catamount', 'raw_catamount__catamount_backcountry_zones') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'catamount_backcountry_zones'",
            geometry_key('geom'),
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
