-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Catamount Trail main route, by surface (the association's web map
-- GeoJSON) (Catamount Trail Association, sources.json
-- `catamount_main_trail`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: The geometry alone: unique on 789 of 793 after 4 exact copies
-- (OBJECTID 52 and 53, 127 and 128, 148 and 149, 259 and 260 repeat a line
-- and its SURFACE), measured 2026-10-04; the features' `id` and OBJECTID
-- are an export's row numbers (decision 40), which duplicates_are_exact
-- sets aside.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('catamount', 'raw_catamount__catamount_main_trail'),
        ['geometry']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'catamount_main_trail'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
