-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The shta/ folder's trail lines layers, conformed to
-- int_trail_lines__unioned's columns: each layer's rename to the union's
-- names and its key, nothing filtered (decision 40; a club's review gate is
-- an intermediate's). The layer's own columns ride whole in `properties`,
-- under dlt's names, so a rule downstream reads a field by the name its
-- registry row gives it: json_merge_patch drops a member a patch sets to
-- null, so `properties` is the base row without the geometry that travels
-- beside it.
select
    'lake_county_superior_hiking_trail' as source_key,
    'shta' as club,
    trail_segment_key,
    cast('Superior Hiking Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_shta__lake_county_superior_hiking_trail),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_shta__lake_county_superior_hiking_trail') }}
union all by name
select
    'shta_line_2025' as source_key,
    'shta' as club,
    trail_segment_key,
    cast(altname as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_shta__shta_line_2025),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_shta__shta_line_2025') }}
union all by name
select
    'shta_spirit_mountain_spur_2025' as source_key,
    'shta' as club,
    trail_segment_key,
    cast(altname as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_shta__shta_spirit_mountain_spur_2025),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_shta__shta_spirit_mountain_spur_2025') }}
union all by name
select
    'shta_spurs_and_loops' as source_key,
    'shta' as club,
    trail_segment_key,
    cast(altname as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_shta__shta_spurs_and_loops),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_shta__shta_spurs_and_loops') }}
