-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Carolina Mountain Club Lookout Tower Challenge
-- (carolinamountainclub.org/hiking/hiking-challenges/...) (Carolina
-- Mountain Club, sources.json `cmc_lookout_towers`): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. A base
-- model, the one place this dataset is staged (decision 34).
--
-- Key: `name`, the tower: unique on all 23 rows read 2026-10-04.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('cmc', 'raw_cmc__cmc_lookout_towers'),
        ['name', 'link']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'cmc_lookout_towers'",
            'name',
        ]) }} as challenge_item_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='challenge_item_key', order_by='_dlt_id'
) }}
