-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The gmc/ folder's points of interest layers, conformed to
-- int_points_of_interest__club_unioned's columns: each layer's rename to
-- the union's names and its key, nothing filtered (decision 40; a club's
-- review gate is an intermediate's). The layer's own columns ride whole in
-- `properties`, under dlt's names, so a rule downstream reads a field by
-- the name its registry row gives it: json_merge_patch drops a member a
-- patch sets to null, so `properties` is the base row without the geometry
-- that travels beside it.
select
    'gmc_map_features' as source_key,
    'gmc' as club,
    poi_key,
    cast(poiname as varchar) as name,
    cast(null as varchar) as category,
    cast(globalid as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_gmc__gmc_map_features),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_gmc__gmc_map_features') }}
union all by name
select
    'gmc_overnight_sites' as source_key,
    'gmc' as club,
    poi_key,
    cast(name as varchar) as name,
    cast(ostype as varchar) as category,
    cast(globalid as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_gmc__gmc_overnight_sites),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_gmc__gmc_overnight_sites') }}
union all by name
select
    'gmc_parking' as source_key,
    'gmc' as club,
    poi_key,
    cast(name as varchar) as name,
    cast(parkintype as varchar) as category,
    cast(globalid as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_gmc__gmc_parking),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_gmc__gmc_parking') }}
union all by name
select
    'gmc_privies' as source_key,
    'gmc' as club,
    poi_key,
    cast(name as varchar) as name,
    cast(privytype as varchar) as category,
    cast(globalid as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_gmc__gmc_privies),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_gmc__gmc_privies') }}
union all by name
select
    'gmc_viewpoints' as source_key,
    'gmc' as club,
    poi_key,
    cast(name as varchar) as name,
    cast(vista as varchar) as category,
    cast(globalid as varchar) as source_id,
    geom,
    json_merge_patch(
        to_json(base_gmc__gmc_viewpoints),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_gmc__gmc_viewpoints') }}
