-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Wilderness Areas along the PCT (CA, OR, WA) (PCTA, sources.json
-- `pcta_wilderness_areas`): every row, keyed and deduped (decision 40),
-- with nothing filtered and nothing joined. A base model, the one place
-- this dataset is staged (decision 34).
--
-- Key: `GlobalID` is unique and non-null on all 253 rows read 2026-10-03.
--
-- Dates: datelastmodified, the layer's esriFieldTypeDate fields
-- (sources.json `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, datelastmodified),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(datelastmodified / 1000) as datelastmodified
    from {{ raw_or_empty(
        source('pcta', 'raw_pcta__pcta_wilderness_areas'),
        ['globalid', 'geometry', 'name', 'datelastmodified:bigint']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'pcta_wilderness_areas'",
            'globalid',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
