-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- CT DEEP trail access points (DEEP Trails Set) (CT DEEP, sources.json
-- `ct_deep_trail_access`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: the geometry with SITENAME: 209 of 209 (measured 2026-10-04 by
-- reading every row and every vertex as the extract reads the layer
-- (f=geojson, outSR 4326), under lib/user_agent.py's USER_AGENT, robots.txt
-- first); SITENAME is null on 9 rows. The geometry alone leaves one pair at
-- one point, two sites under two names.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('ct_deep', 'raw_ct_deep__ct_deep_trail_access'),
        ['sitename', 'geometry', 'parking', 'objectid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ct_deep_trail_access'",
            geometry_key('geom'),
            'sitename',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
