-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Official Designated Connecticut Greenways (CT DEEP, sources.json
-- `ct_deep_greenways`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: the geometry (every vertex as the layer serves it): 120 of 120, no
-- exact copies; 21 rows repeat another's every attribute and differ only in
-- shape (measured 2026-10-03 by reading every row and every vertex as the
-- extract reads the layer (f=geojson, outSR 4326), under
-- lib/user_agent.py's USER_AGENT, robots.txt first). The geometry stands
-- alone because it is the smallest key: phase C's base model keys and
-- dedupes on it.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('ct_deep', 'raw_ct_deep__ct_deep_greenways') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ct_deep_greenways'",
            geometry_key('geom'),
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
