-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- WA Public Lands Inventory 2019 (Washington RCO, sources.json
-- `wa_public_lands_inventory`): every row, keyed and deduped (decision 40),
-- with nothing filtered and nothing joined. A base model, the one place
-- this dataset is staged (decision 34).
--
-- Key: the geometry with Land_Owner, Purchase_Date and FIPS: 32,563 of
-- 32,563 after 30 exact copies, which the base model's dedupe removes
-- (measured 2026-10-03 by reading every row and every vertex as the extract
-- reads the layer (f=geojson, outSR 4326), under lib/user_agent.py's
-- USER_AGENT, robots.txt first). The geometry alone is 32,414: 297 rows
-- share a shape with another, telling themselves apart by owner, purchase
-- date and county (FIPS and its four population columns), the smallest such
-- set of three; 2 rows have no geometry. Reasoned, not asked: one row per
-- owner, purchase and county a parcel spans.
--
-- Dates: disposal_date, the layer's esriFieldTypeDate fields (sources.json
-- `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, disposal_date),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(disposal_date / 1000) as disposal_date
    from {{ source('wa_rco', 'raw_wa_rco__wa_public_lands_inventory') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'wa_public_lands_inventory'",
            geometry_key('geom'),
            'land_owner',
            'purchase_date',
            'fips',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
