-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The nbatc/ folder's trail lines layers, conformed to
-- int_trail_lines__unioned's columns: each layer's rename to the union's
-- names and its key, nothing filtered (decision 40; a club's review gate is
-- an intermediate's). The layer's own columns ride whole in `properties`,
-- under dlt's names, so a rule downstream reads a field by the name its
-- registry row gives it: json_merge_patch drops a member a patch sets to
-- null, so `properties` is the base row without the geometry that travels
-- beside it.
select
    'nbatc_trails' as source_key,
    'nbatc' as club,
    trail_segment_key,
    cast(name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_nbatc__nbatc_trails),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nbatc__nbatc_trails') }}
