-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Protected and Recreational OpenSpace (Polygons) (MassGIS, sources.json
-- `massgis_openspace`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: `OS_ID` is unique and non-null on all 61,486 rows read 2026-10-03.
--
-- Dates: att_date, cal_date_r, the layer's esriFieldTypeDate fields
-- (sources.json `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, att_date, cal_date_r),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(att_date / 1000) as att_date,
        to_timestamp(cal_date_r / 1000) as cal_date_r
    from {{ source('massgis', 'raw_massgis__massgis_openspace') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'massgis_openspace'",
            'os_id',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
