-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- DCR Roads and Trails, statewide (MA DCR) (MA DCR, sources.json
-- `dcr_roads_and_trails`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: GlobalID: unique and non-null on all 36,859 rows (measured
-- 2026-10-03 over every row's attributes).
--
-- Dates: gps_date, the layer's esriFieldTypeDate fields (sources.json
-- `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, gps_date),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(gps_date / 1000) as gps_date
    from {{ source('massgis', 'raw_massgis__dcr_roads_and_trails') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'dcr_roads_and_trails'",
            'globalid',
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
