-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- BLM Alaska fire restrictions (sources.json
-- `blm_fire_restrictions_alaska_fire_service`) in the shape every club
-- notice shares (int_closures__club_notices_unioned): renames and casts
-- only. Each field is read by its own name out of the row as JSON, so a
-- field the source drops or renames reads as null rather than failing every
-- club's build. The reader's shape: extract/_notices.py's PAGE_COLUMNS: one
-- notice a page, its title, its own stated date and the link.
--
-- Only facts cross from base_: the source's id, title, category, status,
-- dates, link, a place name and its own geometry (decision 55, and
-- ORG_NOTICES.md section 7). Classifying a status, holding back an ended
-- notice and placing it are int_closures__club_notices' work.
with base as (
    select *
    from {{ ref('base_blm__blm_fire_restrictions_alaska_fire_service') }}
),

attributes as (
    select *
    from base
),

fields as (
    select
        notice_key,
        key_versions,
        _loaded_at,
        to_json(attributes) as row_json
    from attributes
)

select
    fields.notice_key,
    'blm_fire_restrictions_alaska_fire_service' as source_key,
    'blm' as club,
    'warnings' as notice_type,
    'page_notice' as reader,
    'full' as listing,
    {{ notice_field('url') }} as source_id,
    {{ notice_field('title') }} as title,
    cast(null as varchar) as category,
    cast(null as varchar) as status,
    cast(null as timestamptz) as starts_at,
    cast(null as timestamptz) as ends_at,
    cast(null as timestamptz) as rescinded_at,
    {{ notice_instant(notice_field('date')) }} as source_edited_at,
    {{ notice_field('url') }} as source_url,
    cast(null as varchar) as locality,
    cast(null as varchar) as geom_geojson,
    fields.key_versions,
    fields._loaded_at
from fields
