-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Indiana Trails Inventory, open trails (Indiana DNR) (Indiana DNR,
-- sources.json `in_dnr_open_trails`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: globalid: unique and non-null on all 5,496 rows (measured 2026-10-03
-- over every row's attributes).
--
-- Dates: creationdate, editdate, the layer's esriFieldTypeDate fields
-- (sources.json `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, creationdate, editdate),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(creationdate / 1000) as creationdate,
        to_timestamp(editdate / 1000) as editdate
    from {{ source('hoosier', 'raw_hoosier__in_dnr_open_trails') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'in_dnr_open_trails'",
            'globalid',
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
