"""organization onboarding

Revision ID: d1c4f8a06b93
Revises: b1e4c7a9d2f6
Create Date: 2026-09-17 03:40:00.000000

The twelve tables behind ../../../features/ORG_ONBOARDING.md, plus the
columns it adds to two that already exist. Autogenerated from the models and
then edited by hand for the four things autogenerate cannot know, each of
which is called out where it happens below:

1. **RLS, in this revision rather than a later one.** b3d1c7a94e02's rule and
   tests/test_migration_rls.py's union: PostgREST is a second front door into
   the same Postgres that never passes through FastAPI, so a table created
   without a policy is readable and writable by anyone who views source and
   copies the anon key - and it fails silently rather than loudly. Twelve new
   tables here carry a roster, an org's contact details, volunteers' names and
   a key's allow-list, so there is no table in this revision it would be
   tolerable to leave open.

2. **`clubs` has rows already**, so the two NOT NULL columns added to it take
   a `server_default`. Without one, `ALTER TABLE ... SET NOT NULL` fails
   against any database with a single club in it - which is every database
   `load_assignments.py` has ever been run against.

3. **`slug` is backfilled from `name`.** It is unique and it is in every
   route, so existing rows cannot be left without one. See `_SLUG_BACKFILL`.

**This revision has been re-parented three times, for the same reason every
time.** It was authored against `c9d1a7f48b62`; `b1e4c7a9d2f6` (one flag per
account per note) landed on `main` against that same parent, then
`c3a8f1d6e2b7` (the poi-photo dismissals ledger) landed against
`b1e4c7a9d2f6`, and then `d2f5a8c17b64` (where a report's coordinates came
from) landed against `c3a8f1d6e2b7` - each time producing two heads, which
`alembic upgrade head` refuses to resolve and which every Postgres test in
tests/test_migrations.py and tests/test_schema_drift_check.py fails on. The
third time cost 12 failing tests and was found by running the suite rather
than by reading the diff: a merge that auto-resolves every file cleanly can
still leave two heads, because the two revisions are different FILES naming
the same parent. Stacking on whatever `main` has is the linear answer and
costs nothing here, because a long-lived branch is the only thing that ever
sees this revision before it merges. Expect to do it again if this branch
stays open.

4. **Foreign keys added to existing tables are named.** Autogenerate emits
   `op.create_foreign_key(None, ...)` and then a matching
   `op.drop_constraint(None, ...)`, which is not a thing Alembic can execute:
   the downgrade would raise on the first one. Six of them here are named
   explicitly so the revision is actually reversible, which
   tests/test_migration_expand_contract.py is the standing check on.
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1c4f8a06b93"
down_revision: Union[str, Sequence[str], None] = "d2f5a8c17b64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The tables this revision locks - see b3d1c7a94e02 for the mechanism, and
# note it lists the two it only ADDS COLUMNS to nowhere, because those are
# already locked by that revision. A table is locked once.
RLS_TABLES: tuple[str, ...] = (
    "club_admins",
    "org_parks",
    "org_trails",
    "org_sections",
    "org_roles",
    "role_invites",
    "roster_sync_runs",
    "work_projects",
    "work_project_signups",
    "closure_approvals",
    "console_keys",
    "console_token_grants",
    "ridge_runner_commitments",
    "registry_signoffs",
    "assist_usage",
)


# Postgres's own `regexp_replace`, rather than a Python loop over the rows,
# because this has to work in `alembic upgrade --sql` offline mode where
# there is no connection to read rows through.
#
# Lowercase, non-alphanumerics to hyphens, runs collapsed, ends trimmed, then
# the row's own id appended where two names would collide - a slug is unique
# and "Ramapo Trail Conference" appearing twice is likelier than it sounds
# once orgs are claiming rows a maintainer created. Appending rather than
# refusing means the migration cannot fail on real data; the duplicate gets an
# ugly slug and an admin renames it.
_SLUG_BACKFILL = """
update clubs c set slug = base.candidate || case
        when (select count(*) from clubs o where o.name is not null
              and lower(o.name) = lower(c.name)) > 1
        then '-' || left(c.id, 8)
        else ''
    end
from (
    select id, trim(both '-' from regexp_replace(lower(name), '[^a-z0-9]+', '-', 'g')) as candidate
    from clubs
) base
where base.id = c.id and c.slug is null and base.candidate <> ''
"""


def rls_statements(dialect_name: str, *, enable: bool) -> list[str]:
    """Same shape as b3d1c7a94e02's, for the same testability reason."""
    if dialect_name != "postgresql":
        return []
    verb = "ENABLE" if enable else "DISABLE"
    return [f"ALTER TABLE public.{table} {verb} ROW LEVEL SECURITY" for table in RLS_TABLES]


def upgrade() -> None:
    """Create the twelve tables, widen the two, and lock everything new."""
    op.create_table(
        "club_admins",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("club_id", sa.String(), nullable=False),
        sa.Column("person_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("is_codeowner", sa.Boolean(), nullable=False),
        sa.Column("invited_at", sa.DateTime(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("declined_at", sa.DateTime(), nullable=True),
        sa.Column("decline_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"]),
        sa.ForeignKeyConstraint(["person_id"], ["profiles.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("club_id", "person_id", name="uq_club_admins_club_person"),
    )
    op.create_index(op.f("ix_club_admins_club_id"), "club_admins", ["club_id"], unique=False)
    op.create_index(op.f("ix_club_admins_person_id"), "club_admins", ["person_id"], unique=False)

    op.create_table(
        "org_parks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("club_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("park", "system", "forest", name="parkkind", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_org_parks_club_id"), "org_parks", ["club_id"], unique=False)

    op.create_table(
        "org_trails",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("park_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("blaze_value_raw", sa.String(), nullable=True),
        sa.Column("blaze_mapped", sa.String(), nullable=True),
        sa.Column("miles", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["park_id"], ["org_parks.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_org_trails_park_id"), "org_trails", ["park_id"], unique=False)

    op.create_table(
        "org_sections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("trail_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("start_anchor", sa.String(), nullable=True),
        sa.Column("end_anchor", sa.String(), nullable=True),
        sa.Column("start_mile", sa.Float(), nullable=True),
        sa.Column("end_mile", sa.Float(), nullable=True),
        sa.Column("miles", sa.Float(), nullable=True),
        sa.Column("geometry", sa.Text(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["trail_id"], ["org_trails.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_org_sections_trail_id"), "org_sections", ["trail_id"], unique=False)

    op.create_table(
        "org_roles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("club_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "trail_maintenance",
                "stewards",
                "environmental",
                name="rolecategory",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("reports_to_role_id", sa.String(), nullable=True),
        sa.Column("section_id", sa.String(), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("required_by", sa.String(), nullable=True),
        sa.Column("retired_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"]),
        sa.ForeignKeyConstraint(["reports_to_role_id"], ["org_roles.id"]),
        sa.ForeignKeyConstraint(["section_id"], ["org_sections.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_org_roles_club_id"), "org_roles", ["club_id"], unique=False)
    op.create_index(op.f("ix_org_roles_section_id"), "org_roles", ["section_id"], unique=False)

    op.create_table(
        "role_invites",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("club_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role_id", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("invited_by", sa.String(), nullable=True),
        sa.Column("invited_at", sa.DateTime(), nullable=False),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("claimed_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["claimed_by"], ["profiles.id"]),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"]),
        sa.ForeignKeyConstraint(["invited_by"], ["profiles.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["org_roles.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("club_id", "email", "role_id", name="uq_role_invites_club_email_role"),
    )
    op.create_index(op.f("ix_role_invites_club_id"), "role_invites", ["club_id"], unique=False)
    op.create_index(op.f("ix_role_invites_email"), "role_invites", ["email"], unique=False)

    op.create_table(
        "roster_sync_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("club_id", sa.String(), nullable=False),
        sa.Column("run_by", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("added", sa.String(), nullable=False),
        sa.Column("updated", sa.String(), nullable=False),
        sa.Column("deactivated", sa.String(), nullable=False),
        sa.Column("deactivations_held", sa.String(), nullable=False),
        sa.Column("ran_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"]),
        sa.ForeignKeyConstraint(["run_by"], ["profiles.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roster_sync_runs_club_id"), "roster_sync_runs", ["club_id"], unique=False)

    op.create_table(
        "work_projects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("club_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("meet_point", sa.String(), nullable=True),
        sa.Column("mile", sa.Float(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("upcoming", "completed", "cancelled", name="projectstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("cap", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("ourhike", "mirrored", name="projectsource", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "signup_mode",
            sa.Enum("contact", "in_app", name="signupmode", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("signup_contact", sa.String(), nullable=True),
        sa.Column("signup_url", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"]),
        sa.ForeignKeyConstraint(["created_by"], ["profiles.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_projects_club_id"), "work_projects", ["club_id"], unique=False)
    op.create_index(op.f("ix_work_projects_starts_on"), "work_projects", ["starts_on"], unique=False)

    op.create_table(
        "work_project_signups",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("work_project_id", sa.String(), nullable=False),
        sa.Column("person_id", sa.String(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "interested",
                "confirmed",
                "waitlisted",
                "declined",
                "cancelled_by_volunteer",
                name="signupstate",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("reply_message", sa.Text(), nullable=True),
        sa.Column("replied_by", sa.String(), nullable=True),
        sa.Column("replied_at", sa.DateTime(), nullable=True),
        sa.Column("attended", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["profiles.id"]),
        sa.ForeignKeyConstraint(["replied_by"], ["profiles.id"]),
        sa.ForeignKeyConstraint(["work_project_id"], ["work_projects.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("work_project_id", "person_id", name="uq_work_project_signups_project_person"),
    )
    op.create_index(op.f("ix_work_project_signups_person_id"), "work_project_signups", ["person_id"], unique=False)
    op.create_index(op.f("ix_work_project_signups_work_project_id"), "work_project_signups", ["work_project_id"], unique=False)

    op.create_table(
        "closure_approvals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("closure_id", sa.String(), nullable=False),
        sa.Column("person_id", sa.String(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["closure_id"], ["closures.id"]),
        sa.ForeignKeyConstraint(["person_id"], ["profiles.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("closure_id", "person_id", name="uq_closure_approvals_closure_person"),
    )
    op.create_index(op.f("ix_closure_approvals_closure_id"), "closure_approvals", ["closure_id"], unique=False)
    op.create_index(op.f("ix_closure_approvals_person_id"), "closure_approvals", ["person_id"], unique=False)

    op.create_table(
        "console_keys",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("club_id", sa.String(), nullable=False),
        sa.Column("public_key", sa.String(), nullable=False),
        sa.Column("secret_hash", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("allowed_origins", sa.Text(), nullable=False),
        sa.Column("can_write", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"]),
        sa.ForeignKeyConstraint(["created_by"], ["profiles.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_console_keys_club_id"), "console_keys", ["club_id"], unique=False)
    op.create_index(op.f("ix_console_keys_public_key"), "console_keys", ["public_key"], unique=True)

    op.create_table(
        "console_token_grants",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("club_id", sa.String(), nullable=False),
        sa.Column("console_key_id", sa.String(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("email_hash", sa.String(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"]),
        sa.ForeignKeyConstraint(["console_key_id"], ["console_keys.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_console_token_grants_club_id"), "console_token_grants", ["club_id"], unique=False)
    op.create_index(op.f("ix_console_token_grants_console_key_id"), "console_token_grants", ["console_key_id"], unique=False)

    op.create_table(
        "ridge_runner_commitments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("person_id", sa.String(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("tasks", sa.String(), nullable=False),
        sa.Column("club_id", sa.String(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("ended_early_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"]),
        sa.ForeignKeyConstraint(["person_id"], ["profiles.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ridge_runner_commitments_person_id"), "ridge_runner_commitments", ["person_id"], unique=False)

    # `clubs` already has rows, so the two NOT NULL columns carry a
    # server_default. See point 2 in the module docstring.
    op.add_column("clubs", sa.Column("slug", sa.String(), nullable=True))
    op.add_column("clubs", sa.Column("domain", sa.String(), nullable=True))
    op.add_column("clubs", sa.Column("website", sa.String(), nullable=True))
    op.add_column(
        "clubs",
        sa.Column(
            "verified_by",
            sa.Enum("dns", "email", name="verifiedby", native_enum=False, length=10),
            nullable=True,
        ),
    )
    op.add_column(
        "clubs",
        sa.Column(
            "state",
            sa.Enum("unclaimed", "claimed", "frozen", "deleted", name="orgstate", native_enum=False, length=20),
            nullable=False,
            # Every club that predates this column got here because a
            # maintainer wrote a row - live trails, no admins - which is
            # exactly what `unclaimed` means. The default is not a
            # placeholder; it is the true state of every existing row.
            server_default="unclaimed",
        ),
    )
    op.add_column("clubs", sa.Column("membership_url", sa.String(), nullable=True))
    op.add_column("clubs", sa.Column("donation_url", sa.String(), nullable=True))
    # Consent to the assist panels. Nullable with no server_default, and that
    # is the decision rather than an omission: null means "never agreed", so
    # every row that predates this column - and every row created after it -
    # starts with the panels refusing. See `Club.assist_opted_in`.
    op.add_column("clubs", sa.Column("assist_opted_in_at", sa.DateTime(), nullable=True))
    op.add_column("clubs", sa.Column("assist_opted_in_by", sa.String(), nullable=True))
    op.add_column("clubs", sa.Column("assist_opted_out_at", sa.DateTime(), nullable=True))
    op.add_column("clubs", sa.Column("created_by", sa.String(), nullable=True))
    op.add_column(
        "clubs",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
    )

    # Before the unique index, so a collision surfaces here rather than as a
    # constraint violation with no row named.
    if op.get_context().dialect.name == "postgresql":
        op.execute(_SLUG_BACKFILL)

    op.create_index(op.f("ix_clubs_slug"), "clubs", ["slug"], unique=True)
    op.create_foreign_key("fk_clubs_created_by_profiles", "clubs", "profiles", ["created_by"], ["id"])
    op.create_foreign_key("fk_clubs_assist_opted_in_by_profiles", "clubs", "profiles", ["assist_opted_in_by"], ["id"])

    op.add_column("maintainer_assignments", sa.Column("role_id", sa.String(), nullable=True))
    op.add_column("maintainer_assignments", sa.Column("section_id", sa.String(), nullable=True))
    op.add_column("maintainer_assignments", sa.Column("proposed_by", sa.String(), nullable=True))
    op.add_column("maintainer_assignments", sa.Column("confirmed_by", sa.String(), nullable=True))
    op.add_column("maintainer_assignments", sa.Column("confirmed_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_maintainer_assignments_role_id"), "maintainer_assignments", ["role_id"], unique=False)
    op.create_index(op.f("ix_maintainer_assignments_section_id"), "maintainer_assignments", ["section_id"], unique=False)
    op.create_foreign_key(
        "fk_maintainer_assignments_role_id_org_roles", "maintainer_assignments", "org_roles", ["role_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_maintainer_assignments_section_id_org_sections",
        "maintainer_assignments",
        "org_sections",
        ["section_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_maintainer_assignments_proposed_by_profiles",
        "maintainer_assignments",
        "profiles",
        ["proposed_by"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_maintainer_assignments_confirmed_by_profiles",
        "maintainer_assignments",
        "profiles",
        ["confirmed_by"],
        ["id"],
    )

    op.create_table(
        "registry_signoffs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("club_id", sa.String(), nullable=False),
        sa.Column("person_id", sa.String(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name="fk_registry_signoffs_club"),
        sa.ForeignKeyConstraint(["person_id"], ["profiles.id"], name="fk_registry_signoffs_person"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_registry_signoffs_club_id", "registry_signoffs", ["club_id"])
    op.create_index("ix_registry_signoffs_person_id", "registry_signoffs", ["person_id"])
    # The count that gates publishing is "how many signed THIS registry", so
    # the fingerprint is what the query filters on and what it is indexed for.
    op.create_index("ix_registry_signoffs_fingerprint", "registry_signoffs", ["fingerprint"])

    op.create_table(
        "assist_usage",
        sa.Column("id", sa.String(), nullable=False),
        # Nullable for the public nominate form, which has no organization yet
        # - that is the case it exists to serve, not an oversight.
        sa.Column("club_id", sa.String(), nullable=True),
        sa.Column("client_hash", sa.String(), nullable=True),
        sa.Column("panel", sa.String(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_assist_usage_club_id", "assist_usage", ["club_id"])
    op.create_index("ix_assist_usage_client_hash", "assist_usage", ["client_hash"])
    # The budget query is always "this handle, since this time", so the index
    # that matters is the timestamp one.
    op.create_index("ix_assist_usage_created_at", "assist_usage", ["created_at"])

    for statement in rls_statements(op.get_context().dialect.name, enable=True):
        op.execute(statement)


def downgrade() -> None:
    """Drop the twelve tables and the added columns; the locks go with them.

    Reversible because a migration that cannot be undone is a migration
    nobody dares run. It does destroy an org's registry, roster and roles -
    there is no undo for that beyond a backup, and this docstring is where
    somebody about to run it should find that out.
    """
    op.drop_index("ix_assist_usage_created_at", table_name="assist_usage")
    op.drop_index("ix_assist_usage_client_hash", table_name="assist_usage")
    op.drop_index("ix_assist_usage_club_id", table_name="assist_usage")
    op.drop_table("assist_usage")
    op.drop_index("ix_registry_signoffs_fingerprint", table_name="registry_signoffs")
    op.drop_index("ix_registry_signoffs_person_id", table_name="registry_signoffs")
    op.drop_index("ix_registry_signoffs_club_id", table_name="registry_signoffs")
    op.drop_table("registry_signoffs")
    op.drop_constraint("fk_maintainer_assignments_confirmed_by_profiles", "maintainer_assignments", type_="foreignkey")
    op.drop_constraint("fk_maintainer_assignments_proposed_by_profiles", "maintainer_assignments", type_="foreignkey")
    op.drop_constraint("fk_maintainer_assignments_section_id_org_sections", "maintainer_assignments", type_="foreignkey")
    op.drop_constraint("fk_maintainer_assignments_role_id_org_roles", "maintainer_assignments", type_="foreignkey")
    op.drop_index(op.f("ix_maintainer_assignments_section_id"), table_name="maintainer_assignments")
    op.drop_index(op.f("ix_maintainer_assignments_role_id"), table_name="maintainer_assignments")
    op.drop_column("maintainer_assignments", "confirmed_at")
    op.drop_column("maintainer_assignments", "confirmed_by")
    op.drop_column("maintainer_assignments", "proposed_by")
    op.drop_column("maintainer_assignments", "section_id")
    op.drop_column("maintainer_assignments", "role_id")

    op.drop_constraint("fk_clubs_assist_opted_in_by_profiles", "clubs", type_="foreignkey")
    op.drop_constraint("fk_clubs_created_by_profiles", "clubs", type_="foreignkey")
    op.drop_index(op.f("ix_clubs_slug"), table_name="clubs")
    op.drop_column("clubs", "created_at")
    op.drop_column("clubs", "created_by")
    op.drop_column("clubs", "assist_opted_out_at")
    op.drop_column("clubs", "assist_opted_in_by")
    op.drop_column("clubs", "assist_opted_in_at")
    op.drop_column("clubs", "donation_url")
    op.drop_column("clubs", "membership_url")
    op.drop_column("clubs", "state")
    op.drop_column("clubs", "verified_by")
    op.drop_column("clubs", "website")
    op.drop_column("clubs", "domain")
    op.drop_column("clubs", "slug")

    op.drop_index(op.f("ix_ridge_runner_commitments_person_id"), table_name="ridge_runner_commitments")
    op.drop_table("ridge_runner_commitments")
    op.drop_index(op.f("ix_console_token_grants_console_key_id"), table_name="console_token_grants")
    op.drop_index(op.f("ix_console_token_grants_club_id"), table_name="console_token_grants")
    op.drop_table("console_token_grants")
    op.drop_index(op.f("ix_console_keys_public_key"), table_name="console_keys")
    op.drop_index(op.f("ix_console_keys_club_id"), table_name="console_keys")
    op.drop_table("console_keys")
    op.drop_index(op.f("ix_closure_approvals_person_id"), table_name="closure_approvals")
    op.drop_index(op.f("ix_closure_approvals_closure_id"), table_name="closure_approvals")
    op.drop_table("closure_approvals")
    op.drop_index(op.f("ix_work_project_signups_work_project_id"), table_name="work_project_signups")
    op.drop_index(op.f("ix_work_project_signups_person_id"), table_name="work_project_signups")
    op.drop_table("work_project_signups")
    op.drop_index(op.f("ix_work_projects_starts_on"), table_name="work_projects")
    op.drop_index(op.f("ix_work_projects_club_id"), table_name="work_projects")
    op.drop_table("work_projects")
    op.drop_index(op.f("ix_roster_sync_runs_club_id"), table_name="roster_sync_runs")
    op.drop_table("roster_sync_runs")
    op.drop_index(op.f("ix_role_invites_email"), table_name="role_invites")
    op.drop_index(op.f("ix_role_invites_club_id"), table_name="role_invites")
    op.drop_table("role_invites")
    op.drop_index(op.f("ix_org_roles_section_id"), table_name="org_roles")
    op.drop_index(op.f("ix_org_roles_club_id"), table_name="org_roles")
    op.drop_table("org_roles")
    op.drop_index(op.f("ix_org_sections_trail_id"), table_name="org_sections")
    op.drop_table("org_sections")
    op.drop_index(op.f("ix_org_trails_park_id"), table_name="org_trails")
    op.drop_table("org_trails")
    op.drop_index(op.f("ix_org_parks_club_id"), table_name="org_parks")
    op.drop_table("org_parks")
    op.drop_index(op.f("ix_club_admins_person_id"), table_name="club_admins")
    op.drop_index(op.f("ix_club_admins_club_id"), table_name="club_admins")
    op.drop_table("club_admins")
