-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Ouachita Trail Shelters (Friends of the Ouachita Trail's shelter list)
-- (FoOT, sources.json `foot_trail_shelters`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: `name`: unique on 23 of 23 (measured 2026-10-04 on the live REST
-- answer, parsed as extract/_pages_points.py parses it). `mile_marker` is
-- 23 of 23 too.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('ouachita', 'raw_ouachita__foot_trail_shelters'),
        ['name', 'geometry']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'foot_trail_shelters'",
            'name',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
