-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- AMC Outdoor Itineraries & Trip Ideas
-- (outdoors.org/resources/itineraries/) (AMC, sources.json
-- `amc_itineraries`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: `link`, the trip's own itinerary page: unique on all 10 rows read
-- 2026-10-04, as are the names.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('amc', 'raw_amc__amc_itineraries'),
        ['link', 'name']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'amc_itineraries'",
            'link',
        ]) }} as hike_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='hike_key', order_by='_dlt_id'
) }}
