-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Long Trail system, TRAIL_MASTER (GMC) (GMC, sources.json
-- `gmc_trail_master`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: GlobalID: unique and non-null on all 403 rows (measured 2026-10-03
-- over every row's attributes).
--
-- Dates: lasteddate, the layer's esriFieldTypeDate fields (sources.json
-- `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, lasteddate),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(lasteddate / 1000) as lasteddate
    from {{ raw_or_empty(
        source('gmc', 'raw_gmc__gmc_trail_master'),
        ['globalid', 'geometry', 'trailname', 'lasteddate:bigint']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'gmc_trail_master'",
            'globalid',
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
