-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- GMC Long Trail Side-to-Side Tracker (Long-Trail-Side-to-Side-Tracker.pdf)
-- (GMC, sources.json `gmc_side_to_side`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: `name`, the side trail: unique on all 88 rows read 2026-10-04.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('gmc', 'raw_gmc__gmc_side_to_side'),
        ['name', 'link']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'gmc_side_to_side'",
            'name',
        ]) }} as challenge_item_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='challenge_item_key', order_by='_dlt_id'
) }}
