-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Hike New Mexico trail guide (child pages of nmvfo.org/trails/) (NMVFO,
-- sources.json `nmvfo_hike_new_mexico`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: `id`, the WordPress post id: unique on all 38 rows read 2026-10-04,
-- with X-WP-Total 38 in the same answer. The site's own primary key, never
-- minted again by a reload (decision 40).
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ source('nmvfo', 'raw_nmvfo__nmvfo_hike_new_mexico') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nmvfo_hike_new_mexico'",
            'id',
        ]) }} as hike_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='hike_key', order_by='_dlt_id'
) }}
