-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- GNIS Populated Places (The National Map) (USGS, sources.json
-- `usgs_gnis_populated_places`): every row, keyed and deduped (decision
-- 40), with nothing filtered and nothing joined. A base model, the one
-- place this dataset is staged (decision 34).
--
-- Key: `incounty_id`: unique and non-null on all 176,566 rows (measured
-- 2026-10-03 by reading every row and every vertex as the extract reads the
-- layer (f=geojson, outSR 4326), under lib/user_agent.py's USER_AGENT,
-- robots.txt first), the smallest key; gaz_id repeats once per county a
-- place spans (174,416 distinct, the server's own count), and the geometry
-- alone is 174,319.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('usgs_tnm', 'raw_usgs_tnm__usgs_gnis_populated_places'),
        ['incounty_id', 'geometry', 'gaz_name']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'usgs_gnis_populated_places'",
            'incounty_id',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
