-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Maah Daah Hey Trail and its connectors (the trail guide's 19 GeoJSON
-- files, with elevation) (MDHTA, sources.json `mdhta_trail_guide`): every
-- row, keyed and deduped (decision 40), with nothing filtered and nothing
-- joined. A base model, the one place this dataset is staged (decision 34).
--
-- Key: The geometry alone: unique on 22 of 22 across the 19 files (measured
-- 2026-10-04). `name` is 20 of 22.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('mdhta', 'raw_mdhta__mdhta_trail_guide') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'mdhta_trail_guide'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
