-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Maah Daah Hey trail guide's points: trailheads, campgrounds, water cache
-- boxes, river crossings (MDHTA, sources.json `mdhta_trail_guide_points`):
-- every row, keyed and deduped (decision 40), with nothing filtered and
-- nothing joined. A base model, the one place this dataset is staged
-- (decision 34).
--
-- Key: `link`, each point's own page on mdhta.com (its post permalink):
-- unique on 50 of 50 (measured 2026-10-04 on the live page, every anchor
-- parsed as extract/_pages_points.py parses it). The geometry is 50 of 50
-- too, (`kind`, `name`) 50 of 50 and `slug` 39 of 50, because a trailhead
-- and a campground of one name share a slug.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('mdhta', 'raw_mdhta__mdhta_trail_guide_points'),
        ['link', 'geometry', 'name', 'kind']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'mdhta_trail_guide_points'",
            'link',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
