-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- DCR park alerts and advisories (sources.json `ma_dcr_park_alerts`, landed
-- by extract/ma_dcr/closures.py's ArcgisLayer): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. Its
-- words, prose included, stay here: the staging model beside it carries
-- only facts (decision 55).
--
-- Key: objectid, a server row id, so the geometry joins it (decision 40:
-- never a server row id alone). A reload that mints the ids again reads as
-- every notice removed and added, which moves a row's dates and never its
-- presence. @unvalidated as the smallest set of current values:
-- pipeline/spike_table_keys.py on the live layer settles it. Measured: Read
-- by this step at 2026-10-03T16:09:27Z: returnCountOnly under the row's
-- `where` answered 3, and `OBJECTID` is distinct on 3 of them
-- (returnDistinctValues), the key phase C builds on.
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        {{ notice_row_version(
            source('ma_dcr', 'raw_ma_dcr__ma_dcr_park_alerts')
        ) }} as row_version
    from {{ notice_raw_table(
        source('ma_dcr', 'raw_ma_dcr__ma_dcr_park_alerts'),
        ['geometry', 'objectid']
    ) }}
),

keyed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ma_dcr_park_alerts'",
            'objectid',
            geometry_key('geom'),
        ]) }} as notice_key,
        source.*
    from source
),

-- How many different rows share each key. More than one is what
-- duplicates_are_exact fails on, which only warns for a club notice
-- source: int_closures__gate holds the source instead, so one club's
-- conflicting rows hold that club's notices and nothing else.
renamed as (
    select
        keyed.*,
        count(distinct keyed.row_version)
            over (partition by keyed.notice_key)
            as key_versions
    from keyed
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
