-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Ann and Roy Butler Hike and Bike Trail (The Trail Conservancy) (The Trail
-- Conservancy, sources.json `ttc_butler_trail`): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. A base
-- model, the one place this dataset is staged (decision 34).
--
-- Key: GlobalID_2: unique and non-null on all 237 rows (measured 2026-10-03
-- over every row's attributes).
--
-- Dates: created_date, modified_date, creationdate, editdate, the layer's
-- esriFieldTypeDate fields (sources.json `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (
            geometry,
            created_date,
            modified_date,
            creationdate,
            editdate
        ),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(created_date / 1000) as created_date,
        to_timestamp(modified_date / 1000) as modified_date,
        to_timestamp(creationdate / 1000) as creationdate,
        to_timestamp(editdate / 1000) as editdate
    from {{ source('austin_trail', 'raw_austin_trail__ttc_butler_trail') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ttc_butler_trail'",
            'globalid_2',
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
