-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- TEHCC club wiki announcements (sources.json `tehcc_wiki_announcements`,
-- landed by extract/tehcc/warnings.py's MediawikiAnnouncements): every row,
-- keyed and deduped (decision 40), with nothing filtered and nothing
-- joined. Its words, prose included, stay here: the staging model beside it
-- carries only facts (decision 55).
--
-- Key: pageid. Measured: no count is recorded on its sources.json row
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select *
    from {{ notice_raw_table(
        source('tehcc', 'raw_tehcc__tehcc_wiki_announcements'),
        ['pageid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'tehcc_wiki_announcements'",
            'pageid',
        ]) }} as notice_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
