-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Arizona Trail passages for mountain bikes (ATA) (ATA, sources.json
-- `ata_mountain_bike_passages`): every row, keyed and deduped (decision
-- 40), with nothing filtered and nothing joined. A base model, the one
-- place this dataset is staged (decision 34).
--
-- Key: GlobalID: unique and non-null on all 50 rows (measured 2026-10-03
-- over every row's attributes).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('ata', 'raw_ata__ata_mountain_bike_passages') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ata_mountain_bike_passages'",
            'globalid',
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
