-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- CFPA Trail Notices feed (sources.json `cfpa_trail_notices_feed`) in the
-- shape every club notice shares (int_closures__club_notices_unioned):
-- renames and casts only. Each field is read by its own name out of the row
-- as JSON, so a field the source drops or renames reads as null rather than
-- failing every club's build. The reader's shape: extract/_notices.py's
-- FEED_COLUMNS: an RSS or Atom item's id, title, link, its own dates and
-- categories.
--
-- Only facts cross from base_: the source's id, title, category, status,
-- dates, link, a place name and its own geometry (decision 55, and
-- ORG_NOTICES.md section 7). Classifying a status, holding back an ended
-- notice and placing it are int_closures__club_notices' work.
with base as (
    select *
    from {{ ref('base_cfpa__cfpa_trail_notices_feed') }}
),

attributes as (
    select *
    from base
),

fields as (
    select
        notice_key,
        key_versions,
        _loaded_at,
        to_json(attributes) as row_json
    from attributes
)

select
    fields.notice_key,
    'cfpa_trail_notices_feed' as source_key,
    'cfpa' as club,
    'closures' as notice_type,
    'feed_notices' as reader,
    'window' as listing,
    {{ notice_field('item_id') }} as source_id,
    {{ notice_field('title') }} as title,
    {{ notice_field('categories', as_list=true) }} as category,
    cast(null as varchar) as status,
    {{ notice_instant(notice_field('published')) }} as starts_at,
    cast(null as timestamptz) as ends_at,
    cast(null as timestamptz) as rescinded_at,
    {{ notice_instant(notice_field('updated')) }} as source_edited_at,
    {{ notice_field('link') }} as source_url,
    cast(null as varchar) as locality,
    cast(null as varchar) as geom_geojson,
    fields.key_versions,
    fields._loaded_at
from fields
