-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Tahoe Rim Trail trailheads (TRTA's own layer, newest of three) (TRTA,
-- sources.json `tahoe_rim_trailheads`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: `Name`: 22 distinct of 22, the measurement the row's own notes
-- record from decision 54's wave 1 POI read (returnCountOnly and per-value
-- counts, 2026-10-03, under lib/user_agent.py's USER_AGENT, robots.txt
-- first). `id_field` names the object id (`ObjectId`, which dlt lands as
-- objectid), which a reload mints again (decision 40).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('tahoe_rim', 'raw_tahoe_rim__tahoe_rim_trailheads'),
        ['name', 'geometry', 'objectid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'tahoe_rim_trailheads'",
            'name',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
