-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Tahoe Rim Trail Day Hike Itineraries (tahoerimtrail.org/day-hiking/)
-- (TRTA, sources.json `tahoe_rim_day_hikes`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: `name`, the hike's h3 as its theme page states it ('Lake Aloha
-- Hike'): unique on all 15 rows across the four theme pages read
-- 2026-10-04. No hike has an id or a page of its own.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ source('tahoe_rim', 'raw_tahoe_rim__tahoe_rim_day_hikes') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'tahoe_rim_day_hikes'",
            'name',
        ]) }} as hike_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='hike_key', order_by='_dlt_id'
) }}
