-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Tahoe Rim Trail points of interest (TRTA's own layer) (TRTA, sources.json
-- `tahoe_rim_points_of_interest`): every row, keyed and deduped (decision
-- 40), with nothing filtered and nothing joined. A base model, the one
-- place this dataset is staged (decision 34).
--
-- Key: `Name`: 227 of 227 after 1 exact copy (measured 2026-10-04 by
-- reading every row and every vertex as the extract reads the layer
-- (f=geojson, outSR 4326), under lib/user_agent.py's USER_AGENT, robots.txt
-- first), the smallest key; the geometry alone leaves one point under two
-- names.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('tahoe_rim', 'raw_tahoe_rim__tahoe_rim_points_of_interest'),
        ['name', 'geometry', 'type', 'objectid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'tahoe_rim_points_of_interest'",
            'name',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
