-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- ODT Tracks, the Oregon Desert Trail's sections (ONDA) (ONDA, sources.json
-- `onda_odt_tracks`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: the geometry (every vertex at 6 decimal places): 28 of 28, and no
-- attribute column is unique (measured 2026-10-03 over every row).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('onda', 'raw_onda__onda_odt_tracks') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'onda_odt_tracks'",
            geometry_key('geom'),
        ]) }} as trail_segment_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='trail_segment_key', order_by='_dlt_id'
) }}
