-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- COTREX trailheads (CPW) (Colorado Parks & Wildlife, sources.json
-- `cotrex_trailheads`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: the registry's `id_field`; its row records no measurement of it.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('cotrex', 'raw_cotrex__cotrex_trailheads') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'cotrex_trailheads'",
            'feature_id',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
