-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Colorado Outdoors, the Podcast for Colorado Parks and Wildlife (podcast
-- feed) (Colorado Parks & Wildlife, sources.json
-- `cpw_colorado_outdoors_podcast`): every row, keyed and deduped (decision
-- 40), with nothing filtered and nothing joined. A base model, the one
-- place this dataset is staged (decision 34).
--
-- Key: `guid`: present and unique on all 54 items read 2026-10-04, the
-- feed's own id for an episode, which a podcast app keys on too.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ source('cotrex', 'raw_cotrex__cpw_colorado_outdoors_podcast') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'cpw_colorado_outdoors_podcast'",
            'guid',
        ]) }} as episode_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='episode_key', order_by='_dlt_id'
) }}
