-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- Friends of the Ouachita Trail: Trail Condition Report (sources.json
-- `foot_trail_condition_report`, landed by extract/ouachita/warnings.py's
-- SheetCsvSegments): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. Its words, prose included, stay
-- here: the staging model beside it carries only facts (decision 55).
--
-- Key: table_title, sect, begin_mile, end_mile. Measured: Key:
-- (table_title, sect, begin_mile, end_mile), unique on 184 of 184.
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select *
    from {{ notice_raw_table(
        source('ouachita', 'raw_ouachita__foot_trail_condition_report'),
        ['table_title', 'sect', 'begin_mile', 'end_mile']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'foot_trail_condition_report'",
            'table_title',
            'sect',
            'begin_mile',
            'end_mile',
        ]) }} as notice_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
