-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The cita/ folder's trail lines layers, conformed to
-- int_trail_lines__unioned's columns: each layer's rename to the union's
-- names and its key, nothing filtered (decision 40; a club's review gate is
-- an intermediate's). The layer's own columns ride whole in `properties`,
-- under dlt's names, so a rule downstream reads a field by the name its
-- registry row gives it: json_merge_patch drops a member a patch sets to
-- null, so `properties` is the base row without the geometry that travels
-- beside it.
select
    'des_moines_trails' as source_key,
    'cita' as club,
    trail_segment_key,
    cast(name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_cita__des_moines_trails),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_cita__des_moines_trails') }}
union all by name
select
    'iowa_dnr_state_park_trails' as source_key,
    'cita' as club,
    trail_segment_key,
    cast(trail_name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_cita__iowa_dnr_state_park_trails),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_cita__iowa_dnr_state_park_trails') }}
