-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The azgeo/ folder's places layers, conformed to int_places__unioned's
-- columns: each layer's rename to the union's names and its key, nothing
-- filtered (decision 40; a club's review gate is an intermediate's). The
-- layer's own columns ride whole in `properties`, under dlt's names, so a
-- rule downstream reads a field by the name its registry row gives it:
-- json_merge_patch drops a member a patch sets to null, so `properties` is
-- the base row without the geometry that travels beside it.
select
    'azt_gateway_communities' as source_key,
    'azgeo' as club,
    place_key,
    cast(name as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_azgeo__azt_gateway_communities),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_azgeo__azt_gateway_communities') }}
union all by name
select
    'azt_land_ownership' as source_key,
    'azgeo' as club,
    place_key,
    cast("desc" as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_azgeo__azt_land_ownership),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_azgeo__azt_land_ownership') }}
union all by name
select
    'azt_passage_areas' as source_key,
    'azgeo' as club,
    place_key,
    cast(passage as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_azgeo__azt_passage_areas),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_azgeo__azt_passage_areas') }}
