-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The catamount/ folder's trail lines layers, conformed to
-- int_trail_lines__unioned's columns: each layer's rename to the union's
-- names and its key, nothing filtered (decision 40; a club's review gate is
-- an intermediate's). The layer's own columns ride whole in `properties`,
-- under dlt's names, so a rule downstream reads a field by the name its
-- registry row gives it: json_merge_patch drops a member a patch sets to
-- null, so `properties` is the base row without the geometry that travels
-- beside it.
select
    'catamount_full_route' as source_key,
    'catamount' as club,
    trail_segment_key,
    cast(name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_catamount__catamount_full_route),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_catamount__catamount_full_route') }}
union all by name
select
    'catamount_main_trail' as source_key,
    'catamount' as club,
    trail_segment_key,
    cast('Catamount Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_catamount__catamount_main_trail),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_catamount__catamount_main_trail') }}
union all by name
select
    'catamount_side_trails' as source_key,
    'catamount' as club,
    trail_segment_key,
    cast('Catamount Trail side trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_catamount__catamount_side_trails),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_catamount__catamount_side_trails') }}
