-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- Ozark Highlands Trail alerts posts (sources.json
-- `ohta_trail_alerts_posts`, landed by extract/ohta/closures.py's
-- WordpressPosts): every row, keyed and deduped (decision 40), with nothing
-- filtered and nothing joined. Its words, prose included, stay here: the
-- staging model beside it carries only facts (decision 55).
--
-- Key: id. Measured: Read 2026-10-03: category 18, slug 'trailalerts',
-- X-WP-Total 14, 14 posts, ids unique on 14 of 14; newest modified
-- 2022-03-04 ('Prescribed Burn near Richland Creek').
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        *,
        {{ notice_row_version(
            source('ohta', 'raw_ohta__ohta_trail_alerts_posts')
        ) }} as row_version
    from {{ notice_raw_table(
        source('ohta', 'raw_ohta__ohta_trail_alerts_posts'),
        ['id']
    ) }}
),

keyed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'ohta_trail_alerts_posts'",
            'id',
        ]) }} as notice_key,
        source.*
    from source
),

-- How many different rows share each key. More than one is what
-- duplicates_are_exact fails on, which only warns for a club notice
-- source: int_closures__gate holds the source instead, so one club's
-- conflicting rows hold that club's notices and nothing else.
renamed as (
    select
        keyed.*,
        count(distinct keyed.row_version)
            over (partition by keyed.notice_key)
            as key_versions
    from keyed
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
