-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Special Interest Management Areas (USFS, sources.json
-- `usfs_special_interest_areas`): every row, keyed and deduped (decision
-- 40), with nothing filtered and nothing joined. A base model, the one
-- place this dataset is staged (decision 34).
--
-- Key: `specintmgtareaid` is unique and non-null on all 1,906 rows read
-- 2026-10-03.
--
-- Dates: actiondate, expirationdate, the layer's esriFieldTypeDate fields
-- (sources.json `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, actiondate, expirationdate),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(actiondate / 1000) as actiondate,
        to_timestamp(expirationdate / 1000) as expirationdate
    from {{ raw_or_empty(
        source('usfs', 'raw_usfs__usfs_special_interest_areas'),
        [
            'specintmgtareaid',
            'geometry',
            'areaname',
            'actiondate:bigint',
            'expirationdate:bigint',
        ]
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'usfs_special_interest_areas'",
            'specintmgtareaid',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
