-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Ranger District Boundaries - National Extent (USFS, sources.json
-- `usfs_ranger_districts`): every row, keyed and deduped (decision 40),
-- with nothing filtered and nothing joined. A base model, the one place
-- this dataset is staged (decision 34).
--
-- Key: `rangerdistrictid` is unique and non-null on all 503 rows read
-- 2026-10-03.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('usfs', 'raw_usfs__usfs_ranger_districts'),
        ['rangerdistrictid', 'geometry', 'districtname']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'usfs_ranger_districts'",
            'rangerdistrictid',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
