-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- GMC Trail Updates (sources.json `gmc_trail_alerts`, landed by
-- extract/gmc/closures.py's WordpressPosts): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. Its words, prose
-- included, stay here: the staging model beside it carries only facts
-- (decision 55).
--
-- Key: id. Measured: The category lookup and one page of posts
-- (per_page=100): X-WP-Total 15, 15 posts read, `id` distinct on 15 of 15:
-- the key, with X-WP-Total as the proof.
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        *,
        {{ notice_row_version(
            source('gmc', 'raw_gmc__gmc_trail_alerts')
        ) }} as row_version
    from {{ notice_raw_table(
        source('gmc', 'raw_gmc__gmc_trail_alerts'),
        ['id']
    ) }}
),

keyed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'gmc_trail_alerts'",
            'id',
        ]) }} as notice_key,
        source.*
    from source
),

-- How many different rows share each key. More than one is what
-- duplicates_are_exact fails on, which only warns for a club notice
-- source: int_closures__gate holds the source instead, so one club's
-- conflicting rows hold that club's notices and nothing else.
renamed as (
    select
        keyed.*,
        count(distinct keyed.row_version)
            over (partition by keyed.notice_key)
            as key_versions
    from keyed
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
