-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The fta/ folder's places layers, conformed to int_places__unioned's
-- columns: each layer's rename to the union's names and its key, nothing
-- filtered (decision 40; a club's review gate is an intermediate's). The
-- layer's own columns ride whole in `properties`, under dlt's names, so a
-- rule downstream reads a field by the name its registry row gives it:
-- json_merge_patch drops a member a patch sets to null, so `properties` is
-- the base row without the geometry that travels beside it.
select
    'fta_gateway_communities' as source_key,
    'fta' as club,
    place_key,
    cast(town_name as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_fta__fta_gateway_communities),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_fta__fta_gateway_communities') }}
union all by name
select
    'fta_managed_conservation_areas' as source_key,
    'fta' as club,
    place_key,
    cast(maname as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_fta__fta_managed_conservation_areas),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_fta__fta_managed_conservation_areas') }}
