-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Bartram Trail: sites, markers, properties and routes (Bartram Trail
-- Conference's Google My Map) (Bartram Trail Conference, sources.json
-- `bartram_trail_map`): every row, keyed and deduped (decision 40), with
-- nothing filtered and nothing joined. A base model, the one place this
-- dataset is staged (decision 34).
--
-- Key: The geometry with `description`: unique on 245 of 245 (measured
-- 2026-10-04 on the live export). The geometry alone is 210 of 245, because
-- 35 'Markers' placemarks carry no geometry at all and differ only in their
-- text.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('bartram', 'raw_bartram__bartram_trail_map'),
        ['description', 'geometry', 'name', 'folder']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'bartram_trail_map'",
            geometry_key('geom'),
            'description',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
