-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Bartram Trail section trailheads (Blue Ridge Bartram Trail Conservancy's
-- 13 section pages) (Bartram Trail Conference, sources.json
-- `brbtc_section_trailheads`): every row, keyed and deduped (decision 40),
-- with nothing filtered and nothing joined. A base model, the one place
-- this dataset is staged (decision 34).
--
-- Key: `section`, the page's own section number, 1 to 13: unique on 13 of
-- 13 (measured 2026-10-04 on the live pages, parsed as
-- extract/_pages_points.py parses them). `name` and the geometry are 13 of
-- 13 too.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('bartram', 'raw_bartram__brbtc_section_trailheads'),
        ['section', 'geometry', 'name']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'brbtc_section_trailheads'",
            'section',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
