-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Walk Back in Time: the Trapps Mountain Hamlet Path audio tour (podcast
-- feed) (Mohonk Preserve, sources.json `mohonk_walk_back_in_time_podcast`):
-- every row, keyed and deduped (decision 40), with nothing filtered and
-- nothing joined. A base model, the one place this dataset is staged
-- (decision 34).
--
-- Key: `guid`: present and unique on all 12 items read 2026-10-04, the
-- feed's own id for an episode, which a podcast app keys on too.
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('mohonk', 'raw_mohonk__mohonk_walk_back_in_time_podcast'),
        ['guid', 'title', 'pubdate', 'link', 'enclosure_url']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'mohonk_walk_back_in_time_podcast'",
            'guid',
        ]) }} as episode_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='episode_key', order_by='_dlt_id'
) }}
