-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Place Names (GNIS-derived points), NJDEP Features/Land (NJDEP,
-- sources.json `nj_place_names`): every row, keyed and deduped (decision
-- 40), with nothing filtered and nothing joined. A base model, the one
-- place this dataset is staged (decision 34).
--
-- Key: `FEATURE_ID` is unique and non-null on all 2,641 rows read
-- 2026-10-03.
--
-- Dates: date_created, date_edited, the layer's esriFieldTypeDate fields
-- (sources.json `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, date_created, date_edited),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(date_created / 1000) as date_created,
        to_timestamp(date_edited / 1000) as date_edited
    from {{ source('njgin', 'raw_njgin__nj_place_names') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nj_place_names'",
            'feature_id',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
