-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- State Protected Open Space (Generalized) and Recreation Areas in New
-- Jersey (NJDEP, sources.json `nj_state_open_space`): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. A base
-- model, the one place this dataset is staged (decision 34).
--
-- Key: `GLOBALID` is unique and non-null on all 373 rows read 2026-10-03.
--
-- Dates: last_update, the layer's esriFieldTypeDate fields (sources.json
-- `date_fields`).
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry, last_update),
        st_geomfromgeojson(cast(geometry as varchar)) as geom,
        to_timestamp(last_update / 1000) as last_update
    from {{ raw_or_empty(
        source('njgin', 'raw_njgin__nj_state_open_space'),
        ['globalid', 'geometry', 'feature_name', 'last_update:bigint']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'nj_state_open_space'",
            'globalid',
        ]) }} as place_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='place_key', order_by='_dlt_id'
) }}
