-- GENERATED by pipeline/generate_notice_models.py; do not edit by hand.
--
-- USGS post-fire debris-flow hazard assessments (locations) (sources.json
-- `usgs_pwfdf_assessments`, landed by extract/usgs_tnm/warnings.py's
-- ArcgisLayer): every row, keyed and deduped (decision 40), with nothing
-- filtered and nothing joined. Its words, prose included, stay here: the
-- staging model beside it carries only facts (decision 55).
--
-- Key: objectid, a server row id, so the geometry joins it (decision 40:
-- never a server row id alone). A reload that mints the ids again reads as
-- every notice removed and added, which moves a row's dates and never its
-- presence. @unvalidated as the smallest set of current values:
-- pipeline/spike_table_keys.py on the live layer settles it. Measured: Read
-- by this step at 2026-10-03T16:08:45Z: returnCountOnly under the row's
-- `where` answered 749, and `OBJECTID` is distinct on 749 of them
-- (returnDistinctValues), the key phase C builds on.
--
-- Read through notice_raw_table(): a table a conditions leg has not loaded,
-- or has withdrawn as unreadable, reads as no rows here rather than
-- stopping every other club's closures.
with source as (
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ notice_raw_table(
        source('usgs_tnm', 'raw_usgs_tnm__usgs_pwfdf_assessments'),
        ['geometry', 'objectid']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'usgs_pwfdf_assessments'",
            'objectid',
            geometry_key('geom'),
        ]) }} as notice_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='notice_key', order_by='_dlt_id'
) }}
