-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The nysdec/ folder's places layers, conformed to int_places__unioned's
-- columns: each layer's rename to the union's names and its key, nothing
-- filtered (decision 40; a club's review gate is an intermediate's). The
-- layer's own columns ride whole in `properties`, under dlt's names, so a
-- rule downstream reads a field by the name its registry row gives it:
-- json_merge_patch drops a member a patch sets to null, so `properties` is
-- the base row without the geometry that travels beside it.
select
    'dec_adirondack_park_boundary' as source_key,
    'nysdec' as club,
    place_key,
    cast('Adirondack Park' as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_nysdec__dec_adirondack_park_boundary),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nysdec__dec_adirondack_park_boundary') }}
union all by name
select
    'dec_catskill_park_boundary' as source_key,
    'nysdec' as club,
    place_key,
    cast('Catskill Park' as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_nysdec__dec_catskill_park_boundary),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nysdec__dec_catskill_park_boundary') }}
union all by name
select
    'dec_conservation_easements' as source_key,
    'nysdec' as club,
    place_key,
    cast(facility as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_nysdec__dec_conservation_easements),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nysdec__dec_conservation_easements') }}
union all by name
select
    'dec_lands' as source_key,
    'nysdec' as club,
    place_key,
    cast(facility as varchar) as name,
    cast(category as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_nysdec__dec_lands),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nysdec__dec_lands') }}
union all by name
select
    'dec_wildlife_management_areas' as source_key,
    'nysdec' as club,
    place_key,
    cast(wma as varchar) as name,
    cast(null as varchar) as category,
    geom,
    json_merge_patch(
        to_json(base_nysdec__dec_wildlife_management_areas),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_nysdec__dec_wildlife_management_areas') }}
