-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Save Mount Diablo field guide: Hikes in the Diablo Range (Save Mount
-- Diablo, sources.json `smd_diablo_range_hikes`): every row, keyed and
-- deduped (decision 40), with nothing filtered and nothing joined. A base
-- model, the one place this dataset is staged (decision 34).
--
-- Key: The region's part and the hike's name (`section`, `name`): unique on
-- all 47 rows read 2026-10-04. The name alone is not (Marsh Creek Regional
-- Trail and Morgan Territory Regional Preserve are each listed under two
-- parts), nor the link (one post, '8 great places to hike at sunrise and
-- sunset', is linked by six hikes).
with source as (
    -- A content table carries no geometry and is cast nowhere: each column is
    -- as dlt landed it (a WordPress date a timestamp, a feed's pubDate the
    -- string it states, which a rewrite here would restate), nested as JSON.
    select *
    from {{ raw_or_empty(
        source('smd', 'raw_smd__smd_diablo_range_hikes'),
        ['section', 'name', 'link']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'smd_diablo_range_hikes'",
            'section',
            'name',
        ]) }} as hike_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='hike_key', order_by='_dlt_id'
) }}
