-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- Explore PA Trails access points (PASDA) (PASDA, sources.json
-- `pasda_explore_pa_trail_access`): every row, keyed and deduped (decision
-- 40), with nothing filtered and nothing joined. A base model, the one
-- place this dataset is staged (decision 34).
--
-- Key: the geometry with NAME01 and SUBTYPE_CO: 3,028 of 3,028 after 2
-- exact copies (measured 2026-10-04 by reading every row and every vertex
-- as the extract reads the layer (f=geojson, outSR 4326), under
-- lib/user_agent.py's USER_AGENT, robots.txt first). The geometry alone is
-- 2,864 distinct: 332 rows share a point with another, told apart by name
-- and subtype.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ raw_or_empty(
        source('pasda', 'raw_pasda__pasda_explore_pa_trail_access'),
        ['name01', 'subtype_co', 'geometry', 'objectid_1']
    ) }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'pasda_explore_pa_trail_access'",
            geometry_key('geom'),
            'name01',
            'subtype_co',
        ]) }} as poi_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='poi_key', order_by='_dlt_id'
) }}
