-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- DCNR Maximum Elevations in Pennsylvania Counties 202207 (PASDA) (PASDA,
-- sources.json `pasda_county_max_elevations`): every row, keyed and deduped
-- (decision 40), with nothing filtered and nothing joined. A base model,
-- the one place this dataset is staged (decision 34).
--
-- Key: `POINTID`: unique on all 67 rows (the elevation read's own
-- measurement, 2026-10-03, in `notes`), the layer's own point id.
-- `id_field` names the object id, which a reload mints again (decision 40);
-- County is unique too.
with source as (
    -- dlt lands geometry as GeoJSON text and an ArcGIS date as epoch
    -- milliseconds (extract/_kinds.py's ESRI_TYPES); both are cast here, as
    -- decision 40 has staging do.
    select
        * exclude (geometry),
        st_geomfromgeojson(cast(geometry as varchar)) as geom
    from {{ source('pasda', 'raw_pasda__pasda_county_max_elevations') }}
),

renamed as (
    select
        {{ dbt_utils.generate_surrogate_key([
            "'pasda_county_max_elevations'",
            'pointid',
        ]) }} as elevation_feature_key,
        source.*
    from source
)

{{ dbt_utils.deduplicate(
    relation='renamed', partition_by='elevation_feature_key', order_by='_dlt_id'
) }}
