-- GENERATED by pipeline/make_dbt_staging.py from sources.json
-- and the extract's club folders; edit them or it, never this file.
-- The octa/ folder's trail lines layers, conformed to
-- int_trail_lines__unioned's columns: each layer's rename to the union's
-- names and its key, nothing filtered (decision 40; a club's review gate is
-- an intermediate's). The layer's own columns ride whole in `properties`,
-- under dlt's names, so a rule downstream reads a field by the name its
-- registry row gives it: json_merge_patch drops a member a patch sets to
-- null, so `properties` is the base row without the geometry that travels
-- beside it.
select
    'octa_barlow_road_62' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Barlow Road' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_barlow_road_62),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_barlow_road_62') }}
union all by name
select
    'octa_barlow_road_63' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Barlow Road' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_barlow_road_63),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_barlow_road_63') }}
union all by name
select
    'octa_barlow_road_64' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Barlow Road' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_barlow_road_64),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_barlow_road_64') }}
union all by name
select
    'octa_barlow_road_65' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Barlow Road' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_barlow_road_65),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_barlow_road_65') }}
union all by name
select
    'octa_barlow_road_86' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Barlow Road' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_barlow_road_86),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_barlow_road_86') }}
union all by name
select
    'octa_bonneville_trail_1834_86' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Bonneville Trail of 1834' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_bonneville_trail_1834_86),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_bonneville_trail_1834_86') }}
union all by name
select
    'octa_corral_springs_tracks_2015' as source_key,
    'octa' as club,
    trail_segment_key,
    cast(name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_corral_springs_tracks_2015),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_corral_springs_tracks_2015') }}
union all by name
select
    'octa_hastings_cutoff_route' as source_key,
    'octa' as club,
    trail_segment_key,
    cast(title as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_hastings_cutoff_route),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_hastings_cutoff_route') }}
union all by name
select
    'octa_klamath_fremont_trail_65' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Klamath/Fremont Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_klamath_fremont_trail_65),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_klamath_fremont_trail_65') }}
union all by name
select
    'octa_klamath_fremont_trail_71' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Klamath/Fremont Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_klamath_fremont_trail_71),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_klamath_fremont_trail_71') }}
union all by name
select
    'octa_lockhart_trail_route' as source_key,
    'octa' as club,
    trail_segment_key,
    cast(null as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_lockhart_trail_route),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_lockhart_trail_route') }}
union all by name
select
    'octa_meek_trail_65' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Meek Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_meek_trail_65),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_meek_trail_65') }}
union all by name
select
    'octa_meek_trail_71' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Meek Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_meek_trail_71),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_meek_trail_71') }}
union all by name
select
    'octa_meek_trail_86' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Meek Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_meek_trail_86),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_meek_trail_86') }}
union all by name
select
    'octa_molalla_young_trail_62' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Molalla/Young Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_molalla_young_trail_62),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_molalla_young_trail_62') }}
union all by name
select
    'octa_molalla_young_trail_63' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Molalla/Young Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_molalla_young_trail_63),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_molalla_young_trail_63') }}
union all by name
select
    'octa_naches_pass_trail' as source_key,
    'octa' as club,
    trail_segment_key,
    cast(name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_naches_pass_trail),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_naches_pass_trail') }}
union all by name
select
    'octa_natcon_boardman_tracks_2016' as source_key,
    'octa' as club,
    trail_segment_key,
    cast(name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_natcon_boardman_tracks_2016),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_natcon_boardman_tracks_2016') }}
union all by name
select
    'octa_oregon_trail_71' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Oregon Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_oregon_trail_71),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_oregon_trail_71') }}
union all by name
select
    'octa_oregon_trail_81' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Oregon Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_oregon_trail_81),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_oregon_trail_81') }}
union all by name
select
    'octa_oregon_trail_85' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Oregon Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_oregon_trail_85),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_oregon_trail_85') }}
union all by name
select
    'octa_oregon_trail_86' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Oregon Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_oregon_trail_86),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_oregon_trail_86') }}
union all by name
select
    'octa_oregon_trail_87' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Oregon Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_oregon_trail_87),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_oregon_trail_87') }}
union all by name
select
    'octa_oregon_trail_88' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Oregon Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_oregon_trail_88),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_oregon_trail_88') }}
union all by name
select
    'octa_oregon_trail_89' as source_key,
    'octa' as club,
    trail_segment_key,
    cast('Oregon Trail' as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_oregon_trail_89),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_oregon_trail_89') }}
union all by name
select
    'octa_polylines_oregon_trail_kml' as source_key,
    'octa' as club,
    trail_segment_key,
    cast(name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_polylines_oregon_trail_kml),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_polylines_oregon_trail_kml') }}
union all by name
select
    'octa_whitman_longsegs_2020' as source_key,
    'octa' as club,
    trail_segment_key,
    cast(name as varchar) as name,
    geom,
    json_merge_patch(
        to_json(base_octa__octa_whitman_longsegs_2020),
        '{"geom": null}'
    ) as properties,
    _loaded_at
from {{ ref('base_octa__octa_whitman_longsegs_2020') }}
